"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import sys
sys.setrecursionlimit(2000)

'''
    sys.argv.append('py2app')
    from setuptools import setup
    APP = ['/Users/stephanie/DEV/ODMToolsPython/ODMTools.py']
    LIBS = ['/usr/X11/lib/libfreetype.6.dylib', '/usr/X11/lib/libstdc++.6.dylib', '/usr/X11/lib/libpng15.15.dylib']
    OPTIONS = {'iconfile': '/Users/stephanie/DEV/ODMToolsPython/odmtools/common/icons/ODMTools.icns',
               'includes': ['pymysql', 'sqlalchemy', 'dateutil'], 'frameworks': LIBS}
    extra_options = dict(app=APP, setup_requires=['py2app'], options={'py2app': OPTIONS})
'''




APP = ['/Users/stephanie/DEV/ODMToolsPython/ODMTools.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

setup(name=NAME, **extra_options)