; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "ODMTools"
<<<<<<< HEAD
#define MyAppVersion "1.2.5_Beta"
#define MyAppExeLongName "ODMTools_1.2.5_Beta_win32_x86_64_console.exe"
=======

#define MyAppVersion "1.2.5_Beta"
#define MyAppExeLongName "ODMTools_1.2.5_Beta_win32_x86_64_console.exe"

>>>>>>> logging
#define MyAppPublisher "ODM2"
#define MyAppURL "https://github.com/ODM2/ODMToolsPython"
#define MyAppExeName "ODMTools.exe"
#define MyAppDir "D:\DEV\ODMToolsPython"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{4E5EC22A-DDE2-40A1-BCF5-5595BE768847}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
LicenseFile={#MyAppDir}\LICENSE.txt
OutputBaseFilename={#MyAppName}_{#MyAppVersion}_Console_Installer
SetupIconFile={#MyAppDir}\odmtools\common\icons\ODMTools.ico
Compression=lzma
SolidCompression=yes
OutputDir={#MyAppDir}\setup\Dist
UsePreviousAppDir=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#MyAppDir}\setup\Windows\ODMTools\ODMTools.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyAppDir}\setup\Windows\ODMTools\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

