"""Subclass of MyDialog1, which is generated by wxFormBuilder."""

import wx
import dialogController


# Implementing AddPoints
class MyProject1MyDialog1( dialogController
.MyDialog1 ):
	def __init__( self, parent ):
		dialogController
	.MyDialog1.__init__( self, parent )
	
	# Handlers for AddPoints events.
	def onClick( self, event ):
		# TODO: Implement onClick
		pass
	
	def onClose( self, event ):
		# TODO: Implement onClose
		pass
	
	
