"""Subclass of pnlIntro, which is generated by wxFormBuilder."""

import wx
from  odmtools.view.clsIntro import pnlIntro

# Implementing pnlIntro
class pnlIntro(pnlIntro):
    def __init__(self, parent, id, pos, size, style, name):
        pnlIntro.__init__(parent, id, pos, size, style, name)

    # Handlers for pnlIntro events.
    def OnBtnSaveRadiobutton(self, event):
        # TODO: Implement OnBtnSaveRadiobutton
        pass

    def OnBtnSaveAsRadiobutton(self, event):
        # TODO: Implement OnBtnSaveAsRadiobutton
        pass

    def OnBtnSaveExistingRadiobuton(self, event):
        # TODO: Implement OnBtnSaveExistingRadiobuton
        pass
	
	
