"""Subclass of pnlIntro, which is generated by wxFormBuilder."""

import wx
import wx.wizard as wiz
from odmtools.view.clsIntro import pnlIntro
from wx.lib.pubsub import pub as Publisher


# Implementing pnlIntro
'''class pnlIntro(pnlIntro):
    def __init__(self, parent, id, pos, size, style, name):
        pnlIntro.__init__(parent, id, pos, size, style, name)'''
########################################################################
class pageIntro(wiz.PyWizardPage):
    def __init__(self, parent, title):
        """Constructor"""
        wiz.PyWizardPage.__init__(self, parent)
        self.next = self.prev = None
        sizer = wx.BoxSizer(wx.VERTICAL)
        self.sizer = sizer
        self.SetSizer(sizer)

        title = wx.StaticText(self, -1, title)
        title.SetFont(wx.Font(18, wx.SWISS, wx.NORMAL, wx.BOLD))
        sizer.Add(title, 10, wx.ALIGN_CENTRE | wx.ALL, 5)
        sizer.Add(wx.StaticLine(self, -1), 5, wx.EXPAND | wx.ALL, 5)
        self.pnlIntroduction = pnlIntro(self)#, id=wxID_ANY, name=u'pnlIntro',
                                                 # pos=wx.Point(536, 285), size=wx.Size(439, 357),
                                                  #style=wx.TAB_TRAVERSAL)
        self.sizer.Add(self.pnlIntroduction, 85, wx.ALL, 5)



        self.pnlIntroduction.rbSave.Bind(wx.EVT_RADIOBUTTON, self.OnBtnSaveRadiobutton)
        self.pnlIntroduction.rbSaveAs.Bind(wx.EVT_RADIOBUTTON, self.OnBtnSaveAsRadiobutton)
        self.pnlIntroduction.rbSaveExisting.Bind(wx.EVT_RADIOBUTTON, self.OnBtnSaveExistingRadiobuton)

    def SetNext(self, next):
        self.next = next

    def SetPrev(self, prev):
        self.prev = prev

    def GetNext(self):
       return self.next
    def GetPrev(self):
        return self.prev


    # Handlers for pnlIntro events.
    def OnBtnSaveRadiobutton(self, event):

        print "in saveRadioButton"
        Publisher.sendMessage("wizChangeSave", event = event)
        #event.Skip()

    def OnBtnSaveAsRadiobutton(self, event):
        print "in saveASRadioButton"
        Publisher.sendMessage("wizChangeSave", event = event)        #event.Skip()

    def OnBtnSaveExistingRadiobuton(self, event):
        Publisher.sendMessage("wizChangeSave", event = event)
        print "in saveexistingRadioButton"
        #event.Skip()
	
	
