#----------------------------------------------------------------------
# This file was generated by C:/Users/Jacob/Documents/ODMToolsPython/odmtools/common/icons/img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

arrow_204_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAtElEQVQ4je3NMQrCQBBG4Wcw"
    "IlbiCcTaQoJYh1FvIBbq5cTC0iKFiBD2DJLCQ1jYbwqb2aBhV7QUnG7J/77A/6oTYztirHyw"
    "m4mxbfeOXAxkwEmMXbyJV8ARODgk0m8DIAGawN6HiLEbYKebCdCvgDyNC2AO3J+QZS3e6v4G"
    "TPM0vgI0an8ZA2egC5TAGmh54otrXgBFEkV6ikSh2At4EEJxEKghpcZFaBs8MXYkxg6/Dn/r"
    "HoqdRikc3EBrAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
arrow_204_32 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABVElEQVRYhe2Tu0oDQRRAjyGB"
    "EEQkpYWkFLEQEQsRWQZRQYKFiIWlH2Bt5f9Y+MKgolnGTxB/RFKIOBYW3oVlubuZ2ZUUsqec"
    "OzvncGGhpqamJgdjXWMSb6kDY90C8GasW/4D+Trwaqyb9woQ+RBYBIZVIkR+DywBL1pEI/NB"
    "Ip+To65ErJSQb4h8Ro56WkR2A+cpeUIXeAqJMNZtZuQJPeCsKOAEsMqb3hEiHwDTyvgOOM0N"
    "iKPWB7A3JmK1gvwgjlpfuQGZiLggYk2RR/yuXZPfanI1IBXRB56V8SzwmI4Q+QDoKPevgUNN"
    "DjClHaYe7gA3wJYyfgd2RFokP8qTjw3wiBgBzbJyrwCJaEvEts994FLk3+MuegUERnjLgwI8"
    "I4LkkPMX5BFHrU9gH3hQxhehcgjcQIJs4grYTcmPQ+WlAzIRo7Lyyhjr2sa65sTFNTX/ih+O"
    "HJC2ETm0lAAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
check_mark_3_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA80lEQVQ4jaXSoUvEABTH8Y/H"
    "zT9CDJeMYjHYxqymE9Gi9UD9D7RdMFgsgskscg4Ek8LYn2EcBptgMIgrhhuym9vc4a+9x+/3"
    "fe/B459agCjNYYhBx1yGOAkD/aIxxN2cw7cR94qi6+QJPsuZXqP1t66wi4tysyvgGkdYwcG8"
    "gAeMsIwnLLUBvrCD16LOsI9F3BeQGVUBt0kYTLCBZ4ySMHjHGdbq1qsC9qI0P0zC4AXrSRg8"
    "Rmm+iuOm+6qAPi6jNB/jo+id1PhmAnU6xVuU5jemT9aoJgCcY/MPz89qWQN8qyWblTeITX97"
    "0DatEo47etv1DTcSMIiVWcuyAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
check_mark_3_32 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAB2klEQVRYhe2Xv0ujMRyHH0tz"
    "3CAOzsXpQHDWPWQSdKg4uInioYOo4CCIqDhYkTt0ExwEbzhuk+MU3WIG/wARcXIWcRLpIKaI"
    "Q/PK29Da9O3b3uJneZtvfjwPeZuGwmf+czriDWVsBlgEpoDOlFlF4ADY0VK8RsWsN2gR+JEy"
    "OJ5o7Z9RIeMNmGohvCrDF0h72x+q1CoYvkCaOQF6gduPBrVK4AgY1VI8AgvtFjgCxrQUL659"
    "Cty0S+Cfg5fg/VjvA321JvjHsJnoGvDvH01KawcugREtxbODA+zWg6clcAcMaSmeYrUlYD5k"
    "cojAHvC3Rl+J8rbfRQVlbB7YCoGHCNwDy8CoE/FT0FJcxODfgF8B6wYLLGspntzlMQusxPqu"
    "gc0YPAv8AbpC4fUESsBV1NBSoKUoAJOuby521qF8kfU3Aq8nkAXOlbGD8aKW4hAY0FKYqKaM"
    "zQGrjcLrCUB5O4+VsdOexKU3bp2EF1nIlyUL7CtjN9z5rogytgcYTwIPFYiyBmxXkVgAvrRD"
    "AMo/MEtRQxn7FZhICk8iALCljB12n/NAd7sFMsBvZWwfMNMMHJLfhl3AGZBLW6DYwNyehMwK"
    "hv8KDhIu2kgqGP4O7LhnS/+YpLzuZ5rLG4x0dkhPV4YZAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
csv_64 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAGg0lEQVR4nO2bbYhVRRjHfy6X"
    "ZVk2i6lEQjYDET9olB+kzDSzYMSXKMuSIoRGP/QhCssykyhbxRJEMkgYgl41grIyGUpWC4mQ"
    "EhOzspKyPogtg4jIIsvShzln9+zcOfeec++53tvqHy7cmXnm7X/m5XnmmRlDHRDajAMeBeYD"
    "UwEBlOop08MF4DjwLrDNKnm+wLIBGFNLJqFNO7AWeBroLLRF6TgBPGyV/K7IQnMTILQRwKfA"
    "rCIbkhEXgBVWyXeKKrAtj7DQpgP4guZ0HqAdeFtos7qoAvPO143ALRXSz+K+UjUMVklvB66q"
    "kL5JaNNulXwlQ10VkXkKCG0mAT9TTto5YD3wjlXyVL0Niupqw60vm6qIrquXhDwEbAGe9KLP"
    "AHOtkofraURKfW3AX8CEKqJ1kZBnDVgYiHumEZ0HsEoOAlnKXi+0eb7WejIRILTpAiZ50eeA"
    "92qtOCPOZJTrEdo8V0sFWUfAuEDccatkfy2V5sBADtmNtYyErASEdotGdx6q7xY+eoQ2L+TJ"
    "kEsP+J9gfR4SRiMBkIOE0UoAOBKqaoyjmQBwGuPySgKjnQCA7UKbVNvlUiCgHXhfaDM2lNjq"
    "BBS11XYDq0IJrU7ADvLrAmlYHoos8viqcFglDwht7gYeA7oqiLYxbEJPJXxK1S206bJKnktG"
    "tjQBAFbJXqA3q7zQphPoodxyBejA2TBDaPUpkBvRwekqMhpSo44AGDKlT2eRHZUE5MFlAprd"
    "gGbjkiegJLS5DtgOzCCdkNB2OUNo82/DWpaOfuAz4CmrZJYj+Ioo4fxud9aY95p6G1AjHgf6"
    "gBfrLagEzK4iMwjsB/YBJ3Gj5DpgDnAX5aNmENgNfIRzbA7ijrbn4hypscPjJPB6It/twGKv"
    "rJ3AD9H/NlyHYy3vjirtzoQSlbXBg8BjVsmjgbQNQpsdwEOJuH7gAavkbk/2e2CX0OYPYGsi"
    "frNVEgChTS/lBDxrlTwZpQuchpdse92otAj2AnNSOh/jJi+8KtD5JG5N/O/G6e0xDgM2ET4e"
    "dz6CpAGqe1qBfcCDyWPvyDE6HadPx6RMSeQ5B7zlyS/GGSkHcdPBn24yLssqOSi02Q/cF6Xt"
    "9WQXZepRTqQRsMUq2RcHhDazgQ+B8VHUAPCPl8f3E6xk5HA/ils7kpgPbE6E9zFMwFeJ+ks4"
    "sgpH2hT4IFF5J25BG59ILwETvTwdXngnsIthe34q5ZgVeZ1ixFbfAG7hHZKjsre4ZoQIOGWV"
    "/DMRloQ9Qz6mCG2644BV8rRV8l5gGo6MENpxO0mMY8Ap4JBVMmnNNWT4Q5gAf2j7PsFKZb0R"
    "DdchWCWPWSWXAUsI3x2Yn5AFOMDIrw/lu0NhCBHgH0HlOZJaCHwitBnvJ1glPwbWBfJIoU0y"
    "/HX0A0BoM4XsHyE3QgT4w73SNhjCQuA3oc1Woc1EL+1Nyh2e/nb4DfCtV17DECKgO1I6YuwF"
    "fslZbhfwBPCT0GZGHGmVPEv5FIPECm+VPHKx5j+ECWgD7k80aABYgFuh4+nQh5urPjYAexj+"
    "yh2Ur96hA8sFocZFH2JmStsLQdo2uCba/gCwSp6wSs4DrgCuBK4F7vHyDAA9VskFwNXAzcD1"
    "VskvY4FoPod2lJkpjouGaH9JpBU+EXcdbVk0AoChA8ehoNDmFMP6weE4PRrqI663RAvdSyn1"
    "teMs0l1efEOHP1S2Be4H9gltbgwlRttdXyLqfHLUeLKdOK1waYX6RkyDRmp/SZRwFpyvxcWY"
    "BfwotDkEfIfrcCduhMxm5HCeDfwttNmDM2FPR7LTcGT6arCPpZ4OMY7K2l8hbrMSbtg9VEVu"
    "evSrBgE8Ev3yYiwp7qsUfFJDHWUoAStwW9MM0teE2BJM4iz5dYQi0I/r/LYiCitFvrJnKgkJ"
    "bSYDv3rRR62StxXRiGbikj8VvkxAsxvQbFwmoNkNaDYuE5BRLnRpOU17bBWE2lfWj6wEhC4b"
    "TI6OvlsOkRntq979OOVtBDIREClLv3vRXdSm8l4MrKRcqz0c3RwZgTxrQMjj85rQxvcONRXR"
    "rdCQ0/TzkHxLPpqqBUKbCTi7ZjXl8/88cINVsmwq53o4mfJwKomsz+aKRgeV7xGutUpuCCXk"
    "PW5ag3s3mPZ2MHgft8kwwKtpibn0gMj3t4DwgWgrYg+wJHms5yO3ImSVtMA84GXc3GpFnMVd"
    "llxU7cV5Ta/HY1yE5/NZMYA7rjuCW+3f83wLqfgPIKjI26LOWpcAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
delete_64 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAADZklEQVR4nO2bMWgUQRSGvxwB"
    "RYKERSVEsDQBLVJZaCoRHIMgok1KZYpY2GhhEVC0EQttBLVYkyK1KCKygqSKKVIEixSaUmII"
    "IQwhBBEJweJGXef2srPrbF4k+8E1b9+8+fe/m9nZ250OKiaKkwHgGnAe6PVstgi8AZ4arT5W"
    "pQ2go6rCUZzsBR4DV4FGyTKbwBhw3Wj1PZS2NJUYEMVJF/AOOBmo5DRw1mi1Hqjeb8p+M22J"
    "4gRgnHAnj601bmsHJbgBwBBwuYK6l23toFRhwGib+BOgD9iT8+mzuUVqlyboHBDFSQ/wlVZj"
    "7xmt7hSsdRe47YQ3gcNGq6XyKv8m9C/gREbNVeB+iVr3bds0DdtHMEIbcCgjNlvmEmbbzHr2"
    "UZpOn6QoTnqBLo/UrIVOZxQnRwupSrXN6sOz3rrRajEvacs5IIqTfcALQHl0uBNJgEtGq2/t"
    "EvKGwAj/78lDU/vIVgl5BhwLp0WMLc+hinXAf0XLJBPFSSd/LjU92yunEnqiOPm1LJ8xWm2k"
    "D2bNst3Ah8plbR9D/FlCHwRW0gd3/RCoDZAWIE3WHPADeO3EuoDTTswAUwX6atg6eSvKdfvZ"
    "LFB7EIic2KStk+aH29DrbtAuPT874Wmj1SlfhVUSxckHWv+A6TNazee13fVDoDZAWoA0XrfD"
    "vkRxcgQ444TnjVZTTt5xWv/YmDFazTl5g4B76/veaPUlhF4IbAAwADx3YmO0Xi2GgAdO7BYw"
    "58Su0HyukOYCEMyAXT8EagOkBUhTGyAtQJraAGkB0tQGSAuQpjZAWoA0tQHSAqSpDZAWIE1t"
    "gLQAaWoDpAVIUxsgLUCa2gBpAdLUBkgLkKY2QFqANLvegNAPRydpbnhIs5aRFwOvnNhKRt4o"
    "rQ9Rc1+ALkJQA+ymptzXUoxWhuY7Rnl5S0CwzRFZ/MsQ2EnDp7QW34ZZ31a/fZ1eFKuhP+NQ"
    "7i8M/A1YARacWDcwEcXJAc8awbF9T1gtaRbInlNa8N40FcXJQ+BGxqFNmnt7irzXF4IGzRPP"
    "+hIfGa1u+hQpMgk+ADSwP0OI+5KiJGu0Xjna4j15GK2WgWFgIy9XkA1g2Gr1otDsabR6C5wD"
    "vDvYRpaBc1ajN6U2TkZxsp/mXpyLNGdgdxLaLlaBT8BL4JnRKmvRtSU/AVmqsu/+u8zCAAAA"
    "AElFTkSuQmCC")

#----------------------------------------------------------------------
edit_property_64 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAE2UlEQVR4nO2bXWhcRRTHf7sU"
    "KSFIGVTEB/FBohWRCFIQKZTSmrFFhQqKFPRlQCpFSWuqEquImhBrREFQZFoRpFBEQdrIoH2I"
    "IYZSQsU+SNQitIY81DKE0ocSQvRh5tqb2dmvu9/Z/F9298xh9vz/954zH/dOjhSENhuB54Bn"
    "gX5gE52Hq8B54GvgmFXyWinnXPJFaNMPnAD6Ghpec3EJ2GuVnC7mkIP/yf8E3NykwJqJ68CA"
    "VXIq1pjzt/2vrK0rH2IB2GyVvBo25HE5v5bJA9wB7I815HEFrxvwTMyYx1X7bsD9QpubQmOe"
    "zhzqsiAP9MaM3YQCvhsiTsvAX42PpeG4Cyi45UPEBFi0St5T93CaDKHN71QwunVbChRgXYBW"
    "B9BqrAvQ6gBajXUBWh1Aq9H1AsQmQiUhtNkC3B6Yp62SNvDbTmTuXUfYUjs9laJqAYBh4InA"
    "9ggwE9g+pbH7DDP+f2tC16fAugCtDqDVyFIDfgSuBLbLEb9vgdsy9F8p/qxHJ1ULYJX8pEK/"
    "16sPp/no+hRYF6DVAbQaWWaCe4C7A/Nxq+R84KcAUUNs5TBvlTxegd8CsFgsliyjwPMUzgSn"
    "gfnANkTjZ4KlBHgHmAwvTIgsAnQErJJfVeLX9TWg6wXIkgJfAj8HtksRvyM0uAhW4iS06QPu"
    "BGatkothe05o829gu2KVvLUOAbYUQhuAMeAV3J1ugaeskpNpvzWZAp78OHCIGxwFMCG02Zb2"
    "XXMCePJHgAOR5h4CEdacAMAO3G1fDD3AyUSEqmuA0GY/8GBgHrVKXgj8RmnMcnjcKvlbKQeh"
    "zdvAm2X6uQY8nGUU2EnhTPAocCGw7aH+M8GDMfL+zY8lqyQAVsm3hDZ54I0SffUCg52UAoNW"
    "yQ9Do3/L7Ttg3Oc/AFbJw8C7Zfrs6RQBBq2SH4XGFHmJK3qrRAAOAyNF+lwBjnaCAC+XIf9o"
    "yrxKBJ8SwxSKsALss0qezlID3sPlfBpzEb991P5gJPrwowj5BAeAFaHNkFUSqyRCm2HciPca"
    "N8h/Dh04ExTa9ODI7yjj+gEwlBRGf1eMAhetkp8lTh0lQBXkE7wPvJqIEEMn1AAgE3lwU+Gx"
    "oDCuQkcI4MmfpDryCQ4BLxZrbHsBUuS3Z+xilhJbZ20tgCc/QXbyZ4GdsX2ABDEB2kKUFPlt"
    "Gbs4izsoUZQ8OLLhIYJNQpvwBYimQmjTS23kz1DmyifI4w4YhbYvhDaN3M4qhzFqIz8QOx0S"
    "Q05o8xLwcaTtOm7fbSVjIJXgMrA1PU77VdzfuFMep3Dr94eo7DzTDPBYpeTBbYoeAw7iNg7T"
    "2EjhE6B640xkktKPIw/wglVywYvSB3wD3Fekr6rJA+T9ubq9uCvebExEbLv85zmr5AKAVXLF"
    "KjlH4XtICabJQB58xfcLjgHcc7RmYRn4IWLf7T+/j7T9ErFlJg+pIc+fq9uMWz6ep7G5DzAT"
    "VmmhzS3AFv8zdnecC34n5EueDi2FVcthr+IIMOK3mXpp3LwglnLS/98yqS02oc29uNR4MuU7"
    "BeyuhTykjs62A4Q2J4Cn/c9ZXM7vorAYTwKP10oe2kgAoc0G4B+Kn2L7AzcsTgBTVsnlevxv"
    "Oz0ef4DV5Jdwt/kEcCrcdq8X2kmAOdyqbQm3+judtbJXg/8A18l6Q/S0laAAAAAASUVORK5C"
    "YII=")

#----------------------------------------------------------------------
exit_64 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAGOklEQVR4nO2bf4hURRzAP8lx"
    "yGFmg4mUhEj2R4ERihiFCMUxhJhpIkmJ5UspNZGSoKxDQgq0qMzsajJLQ0WTTJFJpB9qIUZl"
    "IFImh4hI2DUcIscVsvTHzHq7b+ftvvdudl3pPjDc7czsd+Z93/z4zvc7C4MM8r/muiyVhdLz"
    "gSfq1JdGYEwkZ5dmtGQUMBaYFqo3V4Hz8YwhV6MXOegDLgKF0IKbXQGngIeAG10aD7xLQEVk"
    "nQKN5DfgXhNJU5LXJZReBvwOrA/RSDOPgOWxhwfARBLgPeBYiEaaVQEXga+TCk0kC8CeEA01"
    "swIu16hTMTry0KwKGA2MqFHnzhANNasCWoBnkgqF0iOBeSEaalYFAHQIpWcKpcsyhdIC2AmI"
    "EI008zbYCnwO7BdK78WuC3cBC7BTJAj1UsBRYE5Aea3A7dgHD/Lmi9RDAQXsHn4usNwuQAul"
    "O4G9wMgQQuuxBmw2kQxipPgwkTwKzAb+DSEvtAJ6gJcCy6zARPIQsCSErNBTYLWJ5J/xTKH0"
    "EDwHGGfW5kUBd1Nlu0xDyBFwEmujlyGUngD8BfwdS68NpDGnvBXAtwORE1IBK0wky+al28PX"
    "YlfueNox0AZde3OAM3llhFLAF8ABT/4MoN2T/wNwPEsDQmmE0q8IpVtL800ku4GHgd4s8oqE"
    "UEAf8Fx8Pgul24C3E76zMcf8nwSsBjrdmnIFE8njwEKsD6Fa6ooLDbEIrjORrBAMvIr1Icbp"
    "BnblaGeF+7sAOAe8XFpoIrkd2J5VaIgRUPGWhdJTgWcT6m82kezL0oBQegzwSEnWKqH0oiwy"
    "kgihgLbSD0LpYcDH+EdXAejM0cbTWHO4lA1C6ek5ZJURYgp8KJRegl2J24CNwLiEugeB01mE"
    "u7XE97ZbgG1C6fsHYnmGUEA78AdwCfuW4m+qlA05Fr/HSLb7hwF7hdLLSWca95lI7i/NCGkJ"
    "DqtRfhbYX6NOGW61X16j2ihgW0qR54FbSjMa6RDZbSJZy88Xpx24ox6dKdJIBfyU4zuTg/ci"
    "RiMVkMnyc7yJx3gJSaMU0Iu1xDJhInkJWEwdYoJFGqWAE0nzXyjd6ry8SRwENtWnW41TQLXh"
    "3w5sidv3Rdy2uRJr/ganUQr4pUrZXEACLyZVMJHswVqDwWmUAn72ZTorb4b72CGUfqCKjH3A"
    "1tAda4QCLgMnEsokMNz934KdCjf7KpZ4gCpcbgOhqiXoPDpTsV6XSVjffFZOmUgmOSsejX0e"
    "Tb99X7Fomkh2u/sBO3P0w0viCBBK3wZ8A3wHLAWmkC8o8UWC/OHAg56iqcCaKvJ2Abtz9MOL"
    "dwQIpScBX2EjtJuw/rvi0CvQvy/H/4/n9QIXEtqeTuwoXcLzQunDJpL74gUmkrjT5zQCRIkq"
    "rsm54OOvwBhgpYnkuoE24kMovYf+BdCHASaaSJ5J+P584JOMzZ43kax5GHoS+/DngLcyNpAK"
    "p2Sfs7SsGrBDKD00ofxTQCeUpcangPHu76Ecp7e0zASSHqyUycDaeIgcruwKi7FR49z41oCi"
    "UobW2JcHQpbbpkuB7/E4PE0kzwqlX8B6oXJRbRuc5VIz0CmUPm4i6TtQfYC1JqflEeybAgWs"
    "8eJLdTuV1WA4dj2o2DXcjbGnCBgYWUb/zcx4ej1PI4GYgPUEVxSYSJ4mFidIS8UUcPE2r4NR"
    "KP1PnkYCsgA4jP94/A7WYp2SRWAzX5JKYr2LOJfhdqyF2FBdaq5FBbQBe5ypXoaJ5ElsSC41"
    "zXxLrBpjgR+F0muxV2p7XH4rcARrfo9KI+haVQDYc0rx0NTr0mWsgVXrlukVUk8BF5efmKGD"
    "9eIM8D7wOPaKzA3A9cBNwD3Y3xikJtUIEEqPwJ7B62UZpmEf9rbJEbf3lyGUlsAWMl6fq6kA"
    "ofQ47L28ukZoqmCwpvOXvriic6Z2AKuoPaKPxDNqeYTuw15XTbWg1IFjwNwqR+KRwGfUPlle"
    "wMYYK84TiT+bE0rPAz4i3aktNAXsb4NWxi9eFRFKT8E6am6tIWcr9gpPt6+CzyEyBDucOrg6"
    "dkIP1rbflTDkwZ4Q36B6KL4L60o/UC0k75sCs7C3sr2+vDrTB3Q4274C9/CLsFdlD7nsgied"
    "BNa40NoggwySzH9e9sQ8RmVihgAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
minus_6_64 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAADh0lEQVR4nO2bP2gUQRSHvxwh"
    "iEiKIbHQxkKsLESMBJFoIbKFIoKF2GixGrTSQlEsJEXQdIGgjVMYAiJJEfxTjGAhoiJBRCQI"
    "WlmIiJFFjxRySLDYUZfL3l5u3+xOcfvBNbM77/3mtzO7O+/uepQ2W4FpYBio0R2sAK+Ak73E"
    "g9/jV0/p1IjHPF0jvvLdynCN7pn2adR6UxpXgKhsJSWhaLrgaQZEURgMlqOnXJQ2S8BAsq2b"
    "pz9QGVAZUBngW4BvKgN8C/BNZYBvAb6pDPAtwDeVAb4F+KYywLcA33S9AWkFkUJR2qwDtgFb"
    "gA22eRn4BHyMwuBXmXpKMUBpsxE4ARwlLsL2tTi1obR5BcwDd6Mw+Fa0tkINUNpsAq4Bp2g9"
    "6CR9wIj9TCht7gBjURh8KUpjIQYobQDOAdeB/pxh+oAzwHGlzRXgVhQGbgQmcH4TtGt8DrhJ"
    "/sEn6bex5mxspzg1QGmzAXgMHHMZ13IMeGxzOMOZAUqbXuIrP+IqZgojxDPB2dJNC7ReaXMp"
    "o8+bKAyepLSPAe4X6WoCm+tq8wGlzQFgZ0bf9c0NqQYAExlB9qUk3gVczujjmstKm/koDF43"
    "tTfI1r6KTpfAO+BZssHe8adyxJJQA6Zs7iTPiDV2FOh7B+fPpDyKDuLnG+Zhm/sfVttMBzG+"
    "14DxDjo8SGk720F/16TlTtPYivEeAKXNXmA32S9GDWAyOQOUNv3AEmt7yyuCBjAYhUE9oQng"
    "fBtNv4GFKAye90iyK20OAQ8lMRxwOAqDR3k7S5+nQ22OLxP/3kBCjf+7xlYavBmwtc3xzcnp"
    "mQe7zH4KNGQifXQNtD+lcEQapAY435zkQKRBasCysL8LRBqk94CvbY5vV9qI7gG031K305CJ"
    "1IAPbY6/EMZ3oSET6RJ4KezvApEGqQELwA9hDAk/rIbciAyIwqABzEpiCJm1GnLjYgs7hfxt"
    "Lw8rNrcIsQFRGCziZxbM2twiXBUxLgLSx10n1G1OMU4MiMLgMzDqItYaGbU5xTgrY0VhcA+4"
    "4SpeBjdsLie4ruNdASYdx0wyaXM4w6kBtlp0wX5Ej6cmGn/juv56TFQRysKWym8DO4Sh3gKn"
    "U0rgTiislG0FDwEngfc5Qry3fYeKGjwUOAOS2ELlbuAIsB/YzupdXh1YBJ4C94mLloVrK8WA"
    "Zqwhiv8m1In/quNDTkVFRUVFRbfyB9Nuz3Z8NQ+tAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
plus_6_64 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAACjUlEQVR4nO2bMWvbQBTHfxIm"
    "Q+h0kIyl0C3+ECGbPkEx7SoweGihGULpByju1g6FglYX46GztpAP0WyFEOiSFk2m0FCUDncy"
    "jpuovatyz/XdbxL2O+n//ifpng+/hBZUUT4ABsABsAfsAlttY9aAS+ACOAWOgWmVZ2e3BSc3"
    "faiK8j4wBh4BafcavVIDM+CoyrPz1S9/M0AV5WPgPXDv7rV5ZQ4Mqzz7sPzhtdlVRfkcmLB5"
    "yYPOaWJyXLC4A8zMT3yrEuJJcycksHjmP7GZM38Tc6Bf5dl58wiMCSd50LmOARKz1H3m/3/b"
    "21IDD1P0Oh9a8qBzHqToIidUDlJ0hRcqeym6vA2V3R5+a/ufwDvgxBwv0wP2gZE59sGWrws1"
    "vKzy7HXL9x9VUX7BLFE+8P32n3YU0xm+DfjeUUxnhLj+XyMaIC1AmmiAtABpogHSAqSJBkgL"
    "kCYaIC1AGpdfgzXwAv2jxbZur/4yZsfyvNvorb1XWE5qooryyvJib6s8e2Y5xguqKN8AT23G"
    "uDwCJw5jfGGtzcWA1Z2cdcJaW/AvwWiAtABpXAzwvZFqg7U2FwP2Hcb4wlqby2yOzNa1UyFU"
    "5VndFqCKMgWU5XmbQmhkOc7JgB56395l734H+PaHGAV8dTi3E/ElKC1AmmiAtABpogHSAqSJ"
    "BkgLkCYaIC1AmmiA5+ttdxTTGb4NGHQU0xku2+L/wrr9TY5EFeUP1r8P6K64TNENRqFykaK7"
    "q0LlNEW3loXKcYre22vdp9tQamCamqbCmbAYCWZVnp01dcARupEoFObonHUhZDoqh5KKPDNs"
    "ukgXlaDpozsUk+SPw+Xu0dg6uxplAvpszupQo3PpryYPt3SPN4TQPv8Ln1OXKLFpc7EAAAAA"
    "SUVORK5CYII=")

#----------------------------------------------------------------------
star_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABGUlEQVQ4jZ3TvUoDQRAH8F/C"
    "ESxCCNckWKsPkcJS8hSpUvpRpbSWkM7G5kiRN0h38Tms1CqgYBMkZRC0yJ4sSe4Q/zDsMv/5"
    "2pmdWprlR5hggJa/YY0ZRklwviwx/ApnsqNvFT5JyFyGq3A+lPCDuvKyl5gGWZbYtOoV2cer"
    "YX+zGvY3GJcZxW9b4znIa8hcYIoOTnAWpAW1NMu/sUFnNex/VlT0izTL2/hAo3hCA/M0y5t/"
    "cG5iHnzEPTjHIs3y0r8QuEWwtRsAeioaFrherDg0hbeKAHvcoQBPxSXN8nZo2B5XoJhCjFO8"
    "4xqjoJvgHsd4iY0T2/nHjbvFBbqR7g43eNxJtq7bblWMwY5zga79vZklUZn/WucfSr1A3YhO"
    "/qAAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
star_32 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACNUlEQVRYhcWXvWsUQRjGf7sE"
    "OUSCDGIRbITgF4dFyAVJleKKSWsb7aZIm1LEykKC/8ARhjSa1tYJMaQVcp1HMCLYHGIhg4jE"
    "rdRi35XLeB+7cx8+MOzO7Lzv87wz887OJAiUdTVgE9gA6kCNySIDOsAe0PJGZwCJkF8DXgvx"
    "LNAB1r3R3UQiP54hea+IRko+7LHkP6TEoA5szpHPeQzOgNvyfgpcjPCxkRIf/Y43uuuN7gKt"
    "SB/1lLjVngHbPfXn0lYVtTTCCMB6o78UFXnfiXEUIyCMvsA2EaMQI2BX5v0cvNGfgd1pC/D0"
    "j77AM+lTGomy7nfQdga8Bz5KOZXnB+CrN3qoQ2UdwBXgBrAI3JTnInCLIF1DAd+B697oSlGU"
    "hbJOAZ+A+aItnIIasDANcsECQdqHAi4Ah8q6u5NmFp+HwjFQAMBV4EhZtzRB8iXgSHyfw6As"
    "UOQjsTIB8hXyyFW/78PS8DJwoKxbHYN8FTgQX30xah+YB/Zj1oTY7NOz4mMEAFySUhWl7Mru"
    "hCcRAkrZlBHQ9UZ/q8ouNv/8M2IEdKqSV7EdS4Cybk1ZtzaOgLkSAt71IV4m//M1pf4GeOSN"
    "bo+yjRHwdzEp6+4AT4H7QZ8m0FTWvQKeeKNPQttBSJR1Pxl+LnwIvAUeAw9KiP4FvBSh94AX"
    "Q/pmibLuGFgepXRKaKfkd7X/hb2U/Ew/TqrFogO0Urmlrs9YRHE5zVIAOeU2gC2gTdwlYxQy"
    "8b0FNIqT9R8geqRCf2TJFwAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
x_mark_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA30lEQVQ4jaWRMQ6CMBSGP4lp"
    "nEzcmAyjZ8AFjsHMFdwcDZtXYOYYsOgZGAkTIy4OnVxaU0tpIP5Jh+b1/957f+FPbQC6RFyA"
    "KyAW+iRQRI28a8AL2K9sPkaNPATqojv3wBloHYZW1XrTE1iPsqiRTyC1IC2QqlpmGmxA2SUi"
    "jBo5GBBtHrpEhEDpA5yA2oKY5lq9+Wrr2FVDUgVhzuyaYLVcgJ+dHZl4AXZgNdNMWh8gdwRm"
    "B5v7AFWXiJhpYBoSA5Vp0L8ggR1wBB72ngbErElzghswAu+FZwSKmUbr9AHQaWrMEIA/EAAA"
    "AABJRU5ErkJggg==")

#----------------------------------------------------------------------
x_mark_32 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABdUlEQVRYheWXsWrDMBRFT03I"
    "3CGFjob8SL6lJZAtuzPHe6YaTPMt/hFDxg6G7B5Mh0pCTi3pSWBD6V0SIumdY1l5ceC/50m/"
    "ue3WAAfgCGxm4nXABajypgdgZQ0egI+ZwDobi1EBZNbgcWa4HcOyBV4XFDC3OPPNUimBd2CI"
    "AAxqTRmauAqMl8Apb3p9SGvC0gOwz5v+qtYAFK7JvmIGDpA3/RXY498JA1drAE54dsIn0Gq4"
    "TkBiBLfWALQpAvVtt357/NAhMQkHUDXqFIFMKCGBOzmhAyWRSIbDuBXfgWfHPOdVTkUA7/Km"
    "fyFkZ8W5EwnwX4WlCUrEwmMFZkmMQPAcCJtVkoD4EMZKSAS83/OIZpUkIGkyMR0zSkDa4aQd"
    "M1ogpsNJJKIFttbvuQ/ulVA1tikCBXDWEsImM5JQa894HkhCT0SFKtQK4I8S8HPlTrhEwEhE"
    "JgM+pRN1vhJAqemmBC4LChiWfQsq9brIX7OZ6v/BfANr87/zITFiXQAAAABJRU5ErkJggg==")

