#----------------------------------------------------------------------
# This file was generated by img2py2.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

gtk_execute = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAAN1wAADdcBQiibeAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAIqSURBVDiNpZMxSBthFMd/ryhmO4TWoSBYbgqGZpA4dJAgDkKh6NDFIZBBKjh5Y2fdQpcg"
    "3OTo4OFS6ChkCiRySx0OQ48eF1IqTTlTkmg8zeuS2Fji5IMPvv/33v+D9/7/J6rKU2LisYSI"
    "JIEXA/hLVb2xhap6f4AZIAMkC4XCTqfT6Xc6nX6hUNgBksACMPOAM0q2LGuz2Wz+LpfLR77v"
    "n4VhqGEYqu/7Z+Vy+eji4uKnZVmbo5/IcAYislCv1z/3+/2XiUSCOI7p9XoATE1NMTk5Sa/X"
    "Q0R+zM7OvlNVF+DZSDedYrF4cnV1RRRFtNtt4jgmjmPa7TZRFNHtdikWiydA98EQRSS5t7e3"
    "ury8PH9zcwNAFEVN27ZLAFtbW9np6ennAOvr6/OGYayKCKrqDftfajQafc/z1HVddV1X8/n8"
    "IbACrOTz+cPhu+d52mg0+sCSqv6TMQxDFREZ4nQ6/Qf4NrzHcQxAq9Xi8vLy3jyiqohI0jRN"
    "a3t7+3Umk1kEMAyjFQTBF4C5ubm3rVbLADg9Pa3u7+9/9X3/k6p6EwMveCJyEATBh3Q6vTiY"
    "gWGa5gZAs9nk9vYWgCAIPN/3D4bGeiBjqVRyrq+vX4113CASicT3bDb7fpyM9Vwu59RqtXPb"
    "to8rlUp1KGOlUqnatn1cq9XOc7mcA9TvWf9Z2QQ+AmupVGrXcZw7x3HuUqnULrA2yJmjHHls"
    "G0XkDbAxgIeqWh5b99R1/gvrxVyscweMbQAAAABJRU5ErkJggg==")

