#----------------------------------------------------------------------
# This file was generated by C:/Users/Jacob/Documents/ODMToolsPython/odmtools/common/icons/img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

arrow_204_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAtElEQVQ4je3NMQrCQBBG4Wcw"
    "IlbiCcTaQoJYh1FvIBbq5cTC0iKFiBD2DJLCQ1jYbwqb2aBhV7QUnG7J/77A/6oTYztirHyw"
    "m4mxbfeOXAxkwEmMXbyJV8ARODgk0m8DIAGawN6HiLEbYKebCdCvgDyNC2AO3J+QZS3e6v4G"
    "TPM0vgI0an8ZA2egC5TAGmh54otrXgBFEkV6ikSh2At4EEJxEKghpcZFaBs8MXYkxg6/Dn/r"
    "HoqdRikc3EBrAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
arrow_204_32 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABVElEQVRYhe2Tu0oDQRRAjyGB"
    "EEQkpYWkFLEQEQsRWQZRQYKFiIWlH2Bt5f9Y+MKgolnGTxB/RFKIOBYW3oVlubuZ2ZUUsqec"
    "OzvncGGhpqamJgdjXWMSb6kDY90C8GasW/4D+Trwaqyb9woQ+RBYBIZVIkR+DywBL1pEI/NB"
    "Ip+To65ErJSQb4h8Ro56WkR2A+cpeUIXeAqJMNZtZuQJPeCsKOAEsMqb3hEiHwDTyvgOOM0N"
    "iKPWB7A3JmK1gvwgjlpfuQGZiLggYk2RR/yuXZPfanI1IBXRB56V8SzwmI4Q+QDoKPevgUNN"
    "DjClHaYe7gA3wJYyfgd2RFokP8qTjw3wiBgBzbJyrwCJaEvEts994FLk3+MuegUERnjLgwI8"
    "I4LkkPMX5BFHrU9gH3hQxhehcgjcQIJs4grYTcmPQ+WlAzIRo7Lyyhjr2sa65sTFNTX/ih+O"
    "HJC2ETm0lAAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
check_mark_3_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA9ElEQVQ4jaXSoUvEABTH8Y/H"
    "4R+wKIZLRrEYzJYF04lo0TQ4UP8DbRcMFotgGGaRcyAYhv4jxmGwOQwGMRluyG5uc4e/9h6/"
    "3/e9B49/agGCOIUhBh1zGZI8CvWLxhB3cw7fRtIriq6TJ/gsZ3qN1t+6wi4uys2ugGscYQUH"
    "8wIeMMIynrDUBvjCDl6LOsM+FnFfQGZUBdzmUTjBBp4xyqPwHWdYq1uvCtgL4vQwj8IXrOdR"
    "+BjE6SqOm+6rAvq4DOJ0jI+id1LjmwnU6RRvQZzemD5Zo5oAcI7NPzw/q2UN8K2WbFbeIDH9"
    "7UHbtEo46eht1zfVvTCInm1v5AAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
check_mark_3_32 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAB3UlEQVRYhe2Xv0ubQRyHH0OQ"
    "DpLh5pCpUMhs/4cDHSIZ3EpLDjtIG8ggiLTiYIIo6VYQTmiH4ialFb2p7eAfIFI6OYt0OEQc"
    "igRxyL3y5siPy5s36eJneXPf+/E83JvLEXjMf85UvCG0yQA1oALMpMy6AfaAplXyLipmvUE1"
    "YDtlcDzR2jtRIeMNqIwR3pXhC6S97X+71DoYvkCaOQSeAef9Bo1L4AAoWyWvgOqkBQ6ARavk"
    "rWsfAX8mJfDNwVvwcKx3gWKvCf4xHCU/esBVv0lp7cApsGCV/OfgAB8GwdMSuADmrJLXsdoK"
    "8DZkcojAR+Brj74W7W2/iApCmxLQCIGHCFwCq0DZifipWyVPYvCnwOeAdYMFVq2S1+7yWAbW"
    "Yn2/gc0YPAvsA7lQ+CCBFnAWNaySWCXrwCvX9yZ21qF9kc0OAx8kkAV+Cm1kvGiV/AQ8t0r+"
    "impCmzzwblj4IAFob+d3oc2SJ3HqjVsn4UUW8mXJArtCmw13vjsitCkAL5LAQwWivAe2ukhU"
    "gelJCED7B2YlaghtngAvk8KTCAA0hDbz7nMJEJMWyABfhDZF4PUocEh+G+aAYyCftsDNEHML"
    "CZkdDP8V7CVcdJh0MPwdaLrnWP+YpLzuY0bLPRDPdkhdfpQfAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
close_window_32 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABuElEQVRYhc2XIW/CQBTHf71M"
    "oJFL1cQUliXLFK58hdEFU4Hl2yAwZMBXGG5yCZusRhCCrK5Y2ERfGSvXcoWut39SQ969/++u"
    "7z16DqLmeNEABkAPaAENqlUMhMAMGEWBFwM4Yu4CL2Jch0KgGwXexpGdv9dofgjRViTHXrc5"
    "4jlQJO/clnoKO7tP1VJUX+1l1FAWzQEoA7AFlgZxS4mtFGAF3MszLYibAw8St6oKYAt0osBb"
    "R4G3A/pipDPvR4H3GQXeGuhgcBImABt5AMiB2JvnrbsE4A6YNMeLfawYpRBH5hI7kbUXAwD4"
    "BRB55r5JYqc5XnwZQkBSgH15DUcqaw7l2hA0J3GJ+TkA6RrdurzfKwXQVTuwr4kn9C1aCYC2"
    "2jOFuROIomF1FkBRq2W7I50TRhAmAMsCcx99i6YQJ/87TABc4Dpj/szvatd1hytPoUznwIqf"
    "2T4BHnPipiQ7d4FX4OZU4isDcyTRG8lsLxqvPnBL5tSqAEASmiQ9Of8P9S++iGKL/rEiuSDY"
    "UqhI7mq2NFPACDunEAIjJbfUbs0Q6eU0VgBR4G2ANjAEPvibwowl9xBoiyffl7Kpm6x247sA"
    "AAAASUVORK5CYII=")

#----------------------------------------------------------------------
csv_64 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAADLElEQVRYhc2XW4iNURTHf04n"
    "aUxoNw8SEkLSuCReRE0ue1zKA1IeiJ1bSS7x4tIQLyOXGCWbPIzCg5TSzi01XsgtIZ08UB6G"
    "pt24JEnysNdntvF9cz6nmeFfp7332pf1P3uttdf6+pABZV0BWAVsAGqBvllrI/wAngE7vdEu"
    "x3r6dKH8PLA8zyEZRHZ6ow+VW1jMkK+PlL8CLgAfypxVANYBI6XfqKyr8kbvq4TAZmlfANO9"
    "0Z/LKAdAWeeB05GoQVlHVyQKKYdUA2NkeCavckFbiqxBWbcrNwGgX9Rv/wvlEGyfhv3Kuj15"
    "CfQUUm+iNwlAuAnTkwSyTBDjuLJudE8RuAtcB15GvxLwOiLXD1iWbMgKw4rgjW4H5qXNKevG"
    "AM9F58BE3ms+4I0ukRJVve2Ef6CorJsC1EVk+kfz9cq6mgrPbgWavdFdOmYRuAGoSNYOJJms"
    "Dlgi/TaCg30HZgIjCE/1W2AKUAO8B54Q8sFo4CNwpSsChU7Km4Fh3uh6b3Q9sE3kJWCsN3qF"
    "N3olIekAXPZGzwPOyrhJxrdlHJ+dijgKSsAaoEpZ1whUAeNk7pQ32ivrtgITgQEinw/sBm4B"
    "O4CbksoXllOcIHbCS97ob0ADsB3YSDABQgbgjvyrxTKepKwbTIj/NuA+wRxDKiHwRtrxKes2"
    "K+umeqMfeaMXAVui/XO90V+AI97o78CivMo7Exgs7aOUdTXAPWXdRWXdAOAE8FXmFkh7Utrc"
    "1w+/+8BSZd1BYC/wDqgGphPs3Aw8BEbJnr4R+dnKuqI3ul1ZN5RggtyIb6CWUM0UvdGHpYq5"
    "IXMt3uij3uhNhDA9QEeRqoBp0p//N8qRf9NKx/WvBpYp654SksYEkTcp61YS4ryWEOcxLirr"
    "2oDhneSteQjMAmZEsmrgmPTPAS2d9lwtd2ik/FpZApIkSolAnt6EQIs3+mzqzm7CP09G/yWB"
    "r1F/UHcpUtYVCf4F8C2TgHwHJD6xRr4TugNr6Sj5HybCrJLsGNBEeJYfK+suAJ8qVFwgJLCk"
    "DnxFFB099XGaBQ/M8Ub/eu5TnVCqmBWE9PyAyGYVohWwwORYOcBPsqzn6BKYBf8AAAAASUVO"
    "RK5CYII=")

#----------------------------------------------------------------------
delete_64 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAB5ElEQVRYhe2XMS9sQRTHf15E"
    "4YkwIRHkVQqFiFfQqSimQsEXYBpErVArfADRDF+AQjmNSqchohBRCSIhE9nEKzYbUTiX2Ws2"
    "O7sJr7kn2dwz/3PyP/87c2f2TAsNmLJuGNgCNNCWC5cBB6x7oy9TOVsaKD4KHAOddVJLwKQ3"
    "+jyFtzVVALAdFD8ELnLxEWBOcraByRTSpBlQ1vUDdzLc80Yv1cjbBRZlOOCNvm9YgLKuja/T"
    "PAocib8MHNTgmwd2xJ8C8stQ8kaXawpQ1v0BTgFVT3mT5oG/3uibDPiVSxj7xuII91gIfAhQ"
    "1s0Da99YPLM1qVUtABgHpn9AwLTUAqq34SNwKdiQYA/Ac4SkFWjPYf+ASiS3C+gT/1pyHrNg"
    "bBf0BAlL3ui9+IukmbJuEdiVYa83+imM5z/CH7ekk1BZN8j76Qaw6Y0+Cf4XQM5/Zd0EsCHY"
    "qjf6th536gx0ADPyy9ZTBVi2dfsCrCOF+L8vQSGgEFAIKAQUAgoBqReTK6BX/JI8TwIs65pc"
    "gPlmBYR9eyeAN/oVqOpkvNGVCFbOY1TfMcq5WFRAiffebQjYUNZ1Ay9x/XXtN7Ai/jWfs/dh"
    "0auZtM37TRatZQve6C83quhHKImzwBnxTjfVKsIxGysO8AZ48npaqV2i9AAAAABJRU5ErkJg"
    "gg==")

#----------------------------------------------------------------------
downloading_updates_32 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABiUlEQVRYhe2VMUvDQBiGn5Tg"
    "5hJ0cOns1FHE2eH6A9yc9AYF7aSIv8BFQVDU4QQHN3c9tLNIh87+AwflFtdSHJJi2qbtd01a"
    "HfpCILl8d8/DJXwX4JHI2E3gGFgGSj2v28A7cOK0upeuGXjAd4BrYfmu0+qmMIHI2BD4ABaE"
    "Al/AktOqNaqwdxsHpewBJ6ktSwqlAnMecK85UoGJZSYwE5gJ/LlAXyuOjF0F1oAwNbwIHHiu"
    "fQp8pp5bwKvT6i1dFNKfVeDME5aVLOEjoEsg6xOcA5cFCPTmjnhXupJ5GkbGAlwAewXCt51W"
    "bZFAwRID4UMFCpIYCh8pkFNiJFwkMKaECC4W8JQQw70EhBJecIAgMvY2uX9wWtkcEmJ4ZKwC"
    "NiBuRFvJVZEYO60A9uluKldSeJJKh5vViqUSh5GxL8Tt/DEZ885YAimR5zzz4R8cxyXiYxJg"
    "forcDqsVAk1gBaglf/j3FOC15L4ZRMauA0/k/B/GSAuolpxWdaAKNPj9HJMGN4Cq06r+AwL8"
    "evGMYzDKAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
edit_property_64 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACkElEQVRYhe2XO2hUQRSGvw2L"
    "WFjoELtFRCxS6kZEixAVi8HIIliGECSDCBYWFmHBByKCWFmoEBiEYJRoqURHDEpAUCwkpcgS"
    "UCxChGMUCUGWaDFz4+Vm9+4juYuFPwzc+e8c/jPnnHnlAJR1R4FrQBHIkw0EeASMitE/IjIX"
    "xJ9lKJzEW6BPjK4CdOFn3ilxgANAKep04cPeafRGH3n+zn4ptCyh8JNejXg89FfE6BuZqlv3"
    "FeiOc11ZCjaD/w7UXX7Kul3AJmBRjJ4P3O40mxqYF6MX23IAmAJ6gLvASODekCiiBhgJ9nXx"
    "76YAOAtsAT7HuCF8WprFbNsOiNEva3CuBfGmkFaERWAzsCBGVwK3P82mBipi9EKCE6Da0AHg"
    "PmuLcIr1FWGvGB1PaWeLMCkO6REYJKQgxg00sEmiEu+EvaUMPBGjH4O/kPwO/0ezPIyC+AxQ"
    "AFaAYTF6Iq0IjxCWoRg9GzhN88twWoyOH++lIA4+9ePKumpaOG+ztgjv0VwRlqMQK+v2AD/F"
    "6JvKum3ApZgT5SyuYmUx+noQLwIvgCVlXT9wOQhfCGPH0hwYIBxGMe4g6UX4S4yeS4ir0GaA"
    "fuBiGPtdjL6TthPO1eAqtcYmoazbF8S3xugC8Ao4LEZHTmz8PlBHPMIO4Fyc2FAHGoiDf5ic"
    "Tzog4btPWdd2USrrehqITwKD0YMkQj54dQY4DnxT1i23oPsF2CtGAwwDr4HnwEngUEJ8KCkO"
    "PgKj+OcS+I2nu4X2LogDHAPGxehbwNWYxoN64gA5gBD6Ev7F0koaHorR75V1BeATsB1YBk7g"
    "T9MJ4FQ98VUH1gtl3WlgDPgA7MTfoibxj52VNNuN2gkVMI2/LzwVoz82a/gHQHDNOuKv+0AA"
    "AAAASUVORK5CYII=")

#----------------------------------------------------------------------
exit_64 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAADHElEQVRYhc3XS4gcRRwG8J8h"
    "LFFIkEZkE1SCB5UgQaKHVYMERC2EiBdfB1lwC0EIQm5BD0HXBxjxoCCIjS9INL4QNaEP4gMV"
    "YgQ1IUgIIigqQUIdljUsy7J46Oq1MzuzM5l1ox8U01X9f3xV/dW/aviPcV63waKsRhFWMO9s"
    "imEfrO5hcBVeHTL4fG69YsM09sGqIZP0wgdYj7XYPYjDv0lgDhMphj9TDDN4HEfPNYGpppNi"
    "gHQuCazBjqKsQFFWY9jaz2kpoXRiCq/0sbkUdxdltQFPDxL/bAhMphieHdS4KKuT2KvPKg9K"
    "4Diez4HPeJG/9SKkGN4qyuoKPLZU4EE1sDPFMJuTH8BfuW3u4/cE3l8ugQ/RTPsO3I4LcEyP"
    "bVaU1Y6irDalGOYxjsM41dHQuxRvw2e5e2WK4URRVhfiCC7L4+Mphje6+I7gF8zgxhTDH0vN"
    "bpAVGC3KajVeaCVPeLuH/b0YxUYcKMpq3VLBBxHhF+oi07Z9LVe7M5A1srM1dA2+LMrqeIfp"
    "TIphfFAC3eze62G3JSdtY7PFYp1Wa2OoSjivd43/AYfOJtgwBH5KMUw3naKsbm1qQ1b9hFqA"
    "K0bgu1byVep7w8PNWIrhR0wORaAoK0VZXYftS/h833reig3Ykw+fBs+oP0dfLIgrb5e9GMHP"
    "eDG/am441Lvh3Zb/ffl3BPuLsro2xXAqxTBXlNUEvtFH6AuFqCirlzGXYnhoEOa5NvyOi1vD"
    "B7E9a0FRVk/ikS7u0ymGtTrYbcFLRVldPggBjHUkpy7Tu/BU7k/iTmzqFaS9At9mEg2GvazM"
    "4ZYUw+c57hi+7oi3sALtwetxfm63DZmcelXfzFd7KYZD8lHeDQsEUgxzKYbZFMNsnsVyMKoW"
    "5Zrcf1Qt7K5sVwo34UhRVp/gNE5ikb4WEcjqvn+ZyT/F6/gKv6qF+GA3w85CtE5943lgyMRT"
    "uAc357vCb9iDd9Acy7N4rnFo74KN+AhXD5n8KO5KMZzI8S7BftzQsjms/vNyrBuBbRbv60Ex"
    "j4MphtM5FnVNuMg/lXQaHzdF6n+DvwFmLfiTQplM6AAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
minus_6_64 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAB4klEQVRYhe2VP08bQRDFf7Ys"
    "KkuJtnBFkjbiG0ABVNEmikTjOoWzJRJNUlGkioRoIoV2XUBLSgSrVLaLfALLcpXCuKJYUVgp"
    "UgSKm0PHcty/CEPhJ520szsz7+l2dqamrDsG2jwOftQfkRyg3UgYp0B/TsQbwDuApIC+N3p/"
    "HuzKOmIB9XkQZmEhYCFgIaCR73Ibyrol4A1RM3kp2xOiJvbTG/33QQRI8/gAfAWWU1w+AVNl"
    "3S5w5I0ulLfQFSjr6kAXOLyHPMay+HQlJhfJP/BKWbeWsMfeaC/rb0CnSEJBB5gBOwDKOgW8"
    "TnLFi5qy7iolwQx44Y2+VNatU31IbXijB8q658A50Awd6sA4JfDEG30p6y8VyW9iJddJyvm4"
    "AawCK8HBBEBZ1wI2/0PAprKu5Y2+AD4DB8H5qJYVrazTwFliaxDYaXgLrCdtb7S7zznvGbYC"
    "+5c3ei8rQFn3LBAQ5igl4E9gN+VashAWWpijlICwQLflK4O0Ir9BXrMYIQVZERPJUU2AN/of"
    "dyu3DA4kRzUBgu/AsAL5UGIzkStAptsWMC1BPgW2ikzGQgPDG/2bqGH1Crj3gFWJyUVmIwoh"
    "I/k98JHoratYI1GT6hK18cI5SwlIERO/+VkZ0gWeFK4BAu+ABxZWaWAAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
plus_6_64 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACHElEQVRYhe2VMWgUQRSGvxxH"
    "Gq2GcFVQsBIRi1SegSSVDGKZWiFOlSI2Wimk0cYmaAqbSWFabYRTJqkSIcFajniVxXGkEBks"
    "ooVIsNi3OLfO3c5GvFjcDwtv5r33v39338ybUNa9BBY5HbyqnWJxgMV6sHgL7I6o8DxwAyAU"
    "sOuNfjKK6so6cgG1URQchrGAsYCxgHp5SD+UdZPAdbLL5Jxsd8kusW1v9I9/IkAuj1vAY2A6"
    "EnIP6CnrHgCb3ugk3qRfoKyrARvAiwHFc0xLzIbklCL8AueVddeCdccb7cVeA5YKuUfAB7Gv"
    "AGcD35L478oLKOBiWCs3QpXLwJ48W8CxJM8BKxHxbW/0rDd6FmhH/CuSi3BtBfzLoYBOJLnl"
    "jf4q9mrEn4pVAOFqRfydOtAELhUcXQBlXQNY+AsBC8q6hjf6M3AfWC/4D+qibn8AwQz9v+kR"
    "8E3sw2D/OfBa7DPAQ7FrwuG80T2gVyxQdgwbhfVTb/SXYpA3ejO3lXVTgYAYRyUB3wvrqeB4"
    "/cxPiXR5zqVKOCoJKDbox8B+T9Y/AG+Aq4kcfSi7LA6QhjwhusJxMgHe6GP+7NwqWBeOgUiZ"
    "Bc+A28Dlwn5DWZffjrFGa0vuUEwkCEBZd4Fs2g2bAyF6wLw3+lNZYNLAEKImsJMQvgM0U4pD"
    "4hfIISP5JnAHmOP3kfPAO7KJ2UodxZUFRMTkE/CoStEx/iv8AnNvlCWoFOaqAAAAAElFTkSu"
    "QmCC")

#----------------------------------------------------------------------
star_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABGUlEQVQ4jZ3TvUoDQRAH8F/C"
    "ESxCCNckWKsPkcJS8hSpUvpRpbSWkM7G5kiRN0h38Tms1CqgYBMkZRC0yJ4sSe4Q/zDsMv/5"
    "2pmdWprlR5hggJa/YY0ZRklwviwx/ApnsqNvFT5JyFyGq3A+lPCDuvKyl5gGWZbYtOoV2cer"
    "YX+zGvY3GJcZxW9b4znIa8hcYIoOTnAWpAW1NMu/sUFnNex/VlT0izTL2/hAo3hCA/M0y5t/"
    "cG5iHnzEPTjHIs3y0r8QuEWwtRsAeioaFrherDg0hbeKAHvcoQBPxSXN8nZo2B5XoJhCjFO8"
    "4xqjoJvgHsd4iY0T2/nHjbvFBbqR7g43eNxJtq7bblWMwY5zga79vZklUZn/WucfSr1A3YhO"
    "/qAAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
star_32 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACNUlEQVRYhcWXvWsUQRjGf7sE"
    "OUSCDGIRbITgF4dFyAVJleKKSWsb7aZIm1LEykKC/8ARhjSa1tYJMaQVcp1HMCLYHGIhg4jE"
    "rdRi35XLeB+7cx8+MOzO7Lzv87wz887OJAiUdTVgE9gA6kCNySIDOsAe0PJGZwCJkF8DXgvx"
    "LNAB1r3R3UQiP54hea+IRko+7LHkP6TEoA5szpHPeQzOgNvyfgpcjPCxkRIf/Y43uuuN7gKt"
    "SB/1lLjVngHbPfXn0lYVtTTCCMB6o78UFXnfiXEUIyCMvsA2EaMQI2BX5v0cvNGfgd1pC/D0"
    "j77AM+lTGomy7nfQdga8Bz5KOZXnB+CrN3qoQ2UdwBXgBrAI3JTnInCLIF1DAd+B697oSlGU"
    "hbJOAZ+A+aItnIIasDANcsECQdqHAi4Ah8q6u5NmFp+HwjFQAMBV4EhZtzRB8iXgSHyfw6As"
    "UOQjsTIB8hXyyFW/78PS8DJwoKxbHYN8FTgQX30xah+YB/Zj1oTY7NOz4mMEAFySUhWl7Mru"
    "hCcRAkrZlBHQ9UZ/q8ouNv/8M2IEdKqSV7EdS4Cybk1ZtzaOgLkSAt71IV4m//M1pf4GeOSN"
    "bo+yjRHwdzEp6+4AT4H7QZ8m0FTWvQKeeKNPQttBSJR1Pxl+LnwIvAUeAw9KiP4FvBSh94AX"
    "Q/pmibLuGFgepXRKaKfkd7X/hb2U/Ew/TqrFogO0Urmlrs9YRHE5zVIAOeU2gC2gTdwlYxQy"
    "8b0FNIqT9R8geqRCf2TJFwAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
upload_2_32 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABhklEQVRYhe2XP0vDQBiHn5YM"
    "IrhkdnDUpaNrQRyu4FJE3OU2ab+D+AkcBIf4CUQQrHpDwc2hQyepHYs43+IiJYhDLiDx0tzF"
    "tCj0B4Ek9773POTPhdQomTBSAdAFpsCFliIuM0+tJHwVuAaEOXUDHGoppnMXMPBbYCcz1AP2"
    "fSW8BGbA09wDbR8JZwEHeCkJJwEPuLdEoUAJuJfETIFfwJ0lcgUqgDtJWAUqhBdK/BAII7UC"
    "3FUIT2NdJ+qWwtM5wAH2gJPsycBSeAY8ZsbWgXNP4DHw9u04Bp6zRa7rwCbw4imwpaUYFxXZ"
    "bsFCsxRYCiwF/o3AR4m5nXqCMFKXZv9KS6Fy6l6BCbDhCJ+YHmvCSAngAJIrcGS2Rl6DluIT"
    "6JCs50WJgY7pyUsj5To/A1qKHtAk+QcYAePMNjJjTVPrFNvXcJbEE9D26SnKn3gL0vu6tkBu"
    "yooDYAhsA90wUgDvC4B3zf6wFkZqF3jA83moIDHQqmsp+kALGOD2mlUBHgAtLUX/C0NthkAf"
    "/HkLAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
x_mark_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA30lEQVQ4jaWRMQ6CMBSGP4lp"
    "nEzcmAyjZ8AFjsHMFdwcDZtXYOYYsOgZGAkTIy4OnVxaU0tpIP5Jh+b1/957f+FPbQC6RFyA"
    "KyAW+iRQRI28a8AL2K9sPkaNPATqojv3wBloHYZW1XrTE1iPsqiRTyC1IC2QqlpmGmxA2SUi"
    "jBo5GBBtHrpEhEDpA5yA2oKY5lq9+Wrr2FVDUgVhzuyaYLVcgJ+dHZl4AXZgNdNMWh8gdwRm"
    "B5v7AFWXiJhpYBoSA5Vp0L8ggR1wBB72ngbErElzghswAu+FZwSKmUbr9AHQaWrMEIA/EAAA"
    "AABJRU5ErkJggg==")

#----------------------------------------------------------------------
x_mark_32 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABdUlEQVRYheWXsWrDMBRFT03I"
    "3CGFjob8SL6lJZAtuzPHe6YaTPMt/hFDxg6G7B5Mh0pCTi3pSWBD6V0SIumdY1l5ceC/50m/"
    "ue3WAAfgCGxm4nXABajypgdgZQ0egI+ZwDobi1EBZNbgcWa4HcOyBV4XFDC3OPPNUimBd2CI"
    "AAxqTRmauAqMl8Apb3p9SGvC0gOwz5v+qtYAFK7JvmIGDpA3/RXY498JA1drAE54dsIn0Gq4"
    "TkBiBLfWALQpAvVtt357/NAhMQkHUDXqFIFMKCGBOzmhAyWRSIbDuBXfgWfHPOdVTkUA7/Km"
    "fyFkZ8W5EwnwX4WlCUrEwmMFZkmMQPAcCJtVkoD4EMZKSAS83/OIZpUkIGkyMR0zSkDa4aQd"
    "M1ogpsNJJKIFttbvuQ/ulVA1tikCBXDWEsImM5JQa894HkhCT0SFKtQK4I8S8HPlTrhEwEhE"
    "JgM+pRN1vhJAqemmBC4LChiWfQsq9brIX7OZ6v/BfANr87/zITFiXQAAAABJRU5ErkJggg==")

