#----------------------------------------------------------------------
# This file was generated by C:/Users/Jacob/Documents/ODMToolsPython/odmtools/common/icons/img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage


'''
# License

Please carefully understand the license and download the latest icons at ModernUIIcons.com.

## Understand Your Rights
No Attribution and No Derived Works
http://creativecommons.org/licenses/by-nd/3.0/ *

- If your project is open source include this license file in the source.
- Nothing is needed in the front facing project (UNLESS you
  are using any of the icons listed below in the attribution section).
- Commercial use is not only allowed but encouraged. If it is an icon
  in the attribution list below, you still need to attribute those!
- Do not distribute the entire package (I've allowed this dozens of
  times for open source projects, but email me first).

## Creator
- Austin Andrews (@templarian)

## Contributor**
- Jay Zawrotny (@JayZawrotny)
  - A Bunch
- Oren Nachman
  - appbar.chevron.down
  - appbar.chevron.up
  - appbar.chevron.left
  - appbar.chevron.right

## Derived Works
- Alex Peattie
  - Social: http://www.alexpeattie.com/projects/justvector_icons/

## Attribution***
- Kris Vandermotten (@kvandermotten)
  - appbar.medical.pulse
- Constantin Kichinsky (@kichinsky)
  - appbar.currency.rubles
  - appbar.currency.grivna
- Massimo Savazzi (@msavazzi)
  - List of missing exported icons
- Proletkult Graphik, from The Noun Project
  - appbar.draw.pen (inspired)
- Olivier Guin, from The Noun Project
  - appbar.draw.marker
- Gibran Bisio, from The Noun Project
  - appbar.draw.bucket
Andrew Forrester, from The Noun Project
  - appbar.fingerprint

* The license is for attribution, but this is not required.
** Developers and designers that emailed Templarian the source .design icons to be added into the package. PNGs also accepted, but may take longer to be added.
*** Icons I've copied so closely you want to attribute them and are also under the CC license.

Contact
- http://templarian.com/
- admin[@]templarian[.]com

* Does not apply to copyrighted logos
- Skype
- Facebook
- Twitter
- etc...

'''


appbar_exit = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAEwAAABMCAYAAADHl1ErAAAAAXNSR0IArs4c6QAAAARnQU1B"
    "AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAIFSURBVHhe7dqxL8VQGAXwMhiIRCxW"
    "u/gfbDaJgZ2RjbBJzCRiYbQTAzYTsRoMwuQvYBQLCb7T2zZNc9/r/bR17+X8kpN+Da9573i9"
    "7UNCRERERERERERERERElAxkW41ZyZ4Zna1JLs3YimnJvRmtxiQfkrd0z7MFyZcyeExbliWf"
    "ko10z25Kci0ZSfc881lYXlZ+3F6loTB8PYjSfBVWLSuPrbS8MMR7aXOS5z55lZRfENK0MBRg"
    "KytPtbRyYUgwp6fNiqT8ZJE23mEopXrccsqlVQtDdiWNDWbbGOAFb5rRakfSa02D4WzbSEyF"
    "QdPSGoutMHApbd2M7YuxMKgrbSnbti7WwqCutE785KNRHVwlD8xYeJS8mLHWvuTMjE6wZuE0"
    "rHMoWTVjWGy3FZrg8VWjEtwq9MqRxHascqo/xGB0UdiQBO862/e7ppXCYlnD3iWLkvN0z6OY"
    "Fv0gSuuiMCyuuJi4BAVoeC8NT9onfMY8MWMBVzKU3g/WtC3JeLrn5kZybMZ42X5VZFv0gxHz"
    "jasXLEyJhSmFuOjfSZ7MWOtUUn38n2Zb9DXZlvwqnpJKLEyJhSn5LuxCMuGYeQkpzEi46MeG"
    "hSmxMCUWpuT7o5EGFv0rMxZus9QJ8q9FXbNdJV3TGp6SSixMiYUpxbTo4z8IJ82o9pBtiYiI"
    "iIiIiIjoP0uSb+486h8kIozCAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
appbar_folder_open = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAEwAAABMCAYAAADHl1ErAAAAAXNSR0IArs4c6QAAAARnQU1B"
    "AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAF1SURBVHhe7dgtSARRFIbhVcRiMVkE"
    "k5hNFrPJatUg2KwWo2AQo92fbrXYRbAYbCKI1WKyiKDfkRm4XA64K+ucA/M+8LIyt5y9DjNX"
    "BwAAAAAAAAAAAADQQ/PqWX2N0JnqpUl1o7xN+a1e2lTeZgxTL90qbzOGqRMTzee4dDb4EMb9"
    "3X7YMwMjYMNGxIYFqx/EZdcKFW+jrE+1rFDxNss6V2ZNeesRpbjjvcHelf25M6Xum2vRpbnj"
    "veEOlNlW3npEpyqFerBXNdNkP9frEdkdP6dSqIfbUeZQ1WtR7as0ysEelD23FpT9Vsu1qF6U"
    "3e1plMOt2wW5UOX1yLZUKu1g7St7RZUDR3an0rHBylf2X/8Z+B+tqnRssPaQuqHqoaO6VCm1"
    "h9Rp9aS84bvuQy2qlI6azz3lDR/RsUrLXtl2KHxT3vBdZ4flWZXaifKGj2hXpbak7C3pDd91"
    "j8oOzqldKW/4iNqDMwAAAAAAAAAAAAAAaAwG3/13n+Tl3EwfAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
appbar_table_add = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAEwAAABMCAYAAADHl1ErAAAAAXNSR0IArs4c6QAAAARnQU1B"
    "AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACvSURBVHhe7dcxDgMhDARAkv//OWlI"
    "k+ayAutMNNPQnBCsjOEGAAAAAADAP3rMsZPXHD9arfE5R34ksJDAQh36w3fPunLrmlVYSGAh"
    "gYW8w0IqLCSwkMCAk+24stNfm7st7VnTDwksJLBQRQ+7mrPb9xEVFhJYqOJIdre0ZxUWElhI"
    "YKGKHrb72vesOJnAQhVHsrulPauwkMBCAgtV9LDd175nxckEBgAAAAAAJxjjDSINEjo4T82S"
    "AAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
appbar_table_delete = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAEwAAABMCAYAAADHl1ErAAAAAXNSR0IArs4c6QAAAARnQU1B"
    "AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAFLSURBVHhe7dcxTsNAEIVhQ0FDgxCi"
    "SUPFsegoaCPRcAMoOUDOQE3FCaCn5xzwJmalJRonGTkr7bL/Jz3FVqxIfrJnNwMAAAAAAAAA"
    "AMCejpUn5Xp95lsoz8rJ+qxjVtZK+Va+FK80K+tTsWtelK5LWypWRMpmaXlZKY9Kt06VNyUv"
    "JJXmlfWunCtdmyqNsrbwSstDWQ4r7VXZLOtDqaYsW6VqcaZcjYd/XCoX4yESb8DnmdpydMkr"
    "y+bZ1OrZtamybJ5t23J061bJC0llJV5pD0rX7hWvrCQvzf5zQm4Ur6zEvrsbD4H/7Oj3cw6b"
    "LS2Zdc817fSbQGFBFBZUYobt+s3arg/hCQuisKASr2TtZt0zT1gQhQVRWFCJGXboZZ9tRcso"
    "LKjEK1m7WffMExZEYUEUFlRihh162Wdb0TIKAwAAAAAAAACgBcPwA2WBaGJGF6dXAAAAAElF"
    "TkSuQmCC")

