#----------------------------------------------------------------------
# This file was generated by C:\Users\Jacob\Documents\ODMToolsPython\odmtools\common\icons\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage


#----------------------------------------------------------------------
deletered = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAEyklEQVR42rWVWWxUVRjH/3fu"
    "zNyZLtPpAhaqtLZpoYCxLG20iBuVFMMSBAWhCCFWjRGMD/qAMeDy5guCD8aQGCilREJCAEOh"
    "ISKpWqBsCUIzgB0sHWhnpsx0lruf43d7bbBsBRNPcu7cueee73e+/7dcAf/zEHjj+5MBcR/y"
    "/eWQXOA3w+CGeYRpWr2raRt/FGOX1zRWGcx8x2DGHNNkzBCFAYG/uz6CN+bkw58JKArg9oKd"
    "D4CduKAwRZ0nNW07Nprh4Mq163SmbZBy/IX+8hJ4xufDNbUCN/YcJA+2buYo8wF9vYBqAiZN"
    "fyHgK4Bx+HdokVufZe7e/tW9DPcuW/WiAdaS9fgThf5JlXDkeoF4FEZPN25eDl7qjSQWCfzj"
    "jziqyKCqAZoBGASQ6d7hAMoqoXd0QQ0E93NRXOzbs5MNGw+99nq7lF8wK3fGNAiebNLnIhF7"
    "EJVlBAfijTPbWrfZMVi4bBPmVmyERySJdAIQRKWp01RkYOLTMENJpNtPhnwH9haFFyx5VnA6"
    "f8ucWglPJYXv5GmikfdMR7csHy/9af8LI4JsXfiipd9jZlEjLBdVgij/eKKRJwr9PjYepi5h"
    "8Ncz/UKGd6x/Xh0QiwEdnSQpbVHT+FORP5l8tPXru7Jo+IbXLapFofdblOZNg+SwvdAIpjEb"
    "6MkCJk8DskiO9g7gRh8lnwhlMIkeVV5Q8fORg/dM0zsf8NpXVuHJnB0ozqE/lKUyHdGwRO+n"
    "0xI4kQb+uj60NdwXxbV0qrTaVLrvWwf3W1Cn125xe5LrwCh1oymCkXGdvDGFoWToT6QQ5pgy"
    "VUlcfGChPWgxDjHkm//SOIQpiJFBohJA50PxkVMyAtw8XKXK9f8JkIIY9C6sKxbGU420Hbfl"
    "MQigEUAzrfwjZhpBxr6o5trGRwIocO2SXn3uTVQUAK3HbVko3pDpwkW7XqyKoHklGUcYjupa"
    "6J0PBTAgbhLKyzY6ltcC+w6REYd9ajLe35sI5bodBS6Pxw1GW00+VDftmhKfDcM/KoDBOV3w"
    "ZZ/Gl28DLbttza00VTnS129hQIE3DVZQ5HD0ZGZm2JIxTnUg4xj4lnoYHz4QwOHk+O5ToHkH"
    "SWLaxi29+xIIhbX1RdC2Wu9dgLt4ooCg0+MdAkAQcFZJIQTUzIdx6p4ADuE0Nrw3HQFavxkl"
    "95nd/NI6Yl0DnbnQq/+98RxcKybRUSRPhl0vuoK9jJ1aCqPmLgCH1ID6WU14imQ8d8FuD1ZP"
    "orw3rgxQV9B9Y6Al7nS/A+7l1eAtDokgLgGB5CB5J9QsgXnqDoDrBDZ/UIO2Q3bV0qlh0k1c"
    "xcAf0U350D+/XxqehLuZICuQRd8TQ0azorc2gM0bCSgu41g2Bbh01a7WFDU5bkI72xeTUnIu"
    "RhldEK9OzMouhceJ85EIeSHmNcC8dRswoYRjdh6Q1Gzdre8BBTbZFVuZDW3XaIAjcJZUgXWP"
    "KchDLBXHfpk1rIbZfBvgzm7B4orlQ93T6qJJFVp7zxmJaTNGMz48foHrm+e9zvXIcGB7NL1r"
    "DfjKkVk0bsw1lOVMwKAKMxBtcyrpuQ9rfHgEIMTKS8bm/BDs71wLXj0CYA0qtGcoXSMi9CuP"
    "atwaP8Lxcp3kPHpA1ZtWg79lPfsbqyFD2gLi1v8AAAAASUVORK5CYII=")

