#----------------------------------------------------------------------
# This file was generated by img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

back = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAB2ElEQVR4nKWTwWoTURSG/5Nk"
    "MklJp4YkQxPb2EyqkdRljctWweITuLDqG+jGN/ABxI2Imy4KukgfIQi6sVjqQpF0Ua0IioQa"
    "amQkM3Pu3OPCqRpJUtR/c/m55/vPgXMv8J+Kj7tMreTLcScdhnv9YFRNbAy8ICLbRPRx+mr5"
    "2l8FpFbyNQAtIipUzxSs+mJxYVQADYEdEXlCRLMnajk5uzRHO687mzsvP7W1lioRzQPYTSaN"
    "+73mhw36A54F8BRAZaaaReO8Ax0K3u12cfC5j1Q6CTNlwDQMBEG4v3X7uZ04hM2LuZKIPCai"
    "SnFuShaXKhQqEcVC06Ws5AtTFLIIs5BiEdVXAIBEBNtE1AJw0p6x0Fh2SIeAYk2KBeoHNOgD"
    "/SsAwDqAeq6YkXMXHNIhRLEmFU2gWEdn5AMtzDKwhdX0ZPJRY9mBaAIHQhwI2NfEvgb7Quz/"
    "5gMhrYh/TuC3ul0fWH1byzdt27pnmsnSQMdoAt9TyvP4veLwVcBqc+ga52+ezlrWxB3LylzX"
    "IWKKBa7rPev13Fue67c7D/e+jn0Hh6reqF+yMpkHibhR/uZ6G+27Ly4Pqxv5Fw629t/ETk2s"
    "KdZZZj35ZbvTHFV7pI5dKR//Z/gofQfXpgTqXwL9LQAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
filesave = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACbElEQVR4nK2SuWtUURTGf/e9"
    "N1uSMRkTjcEEt+CCuIAYIagIWgQLEf8Et0ILQUQFOyvtBCsRbUSwETRapNEqkowgLqAE96hJ"
    "NJNZ3rvzZt5277MQJolJI3jK83F+fOc7B/6hVgwcz/3dEwA9h06nmtdt77cr5S4/DFfu7jS2"
    "HOtf24OV7k6n090dudb0srYWBt/84tHbGRLN2ZOPzx282QAs2bqvb92WXfnzZy/iyBoyMjjV"
    "14SZSpNMWtwZypNJmnS257jy4AUJQzNemGl/df1MyQBA4xjE5LJtzJSLfPj8HulKajUXgKPX"
    "7nF76BlKRZRtm1JVEvqBALAAhGHUa75H0bb5WSwyPjGFoBeBAAwiaZNJJQjCCNuVJERMqOOg"
    "AdBh3VNBgFuvMV0q83VyEqVBCPEnKadKpDRohV2tYokYM5X2Zx0I4fphhKy5TBWmGfv0kVw2"
    "SSrbAnXJkxsXyGQyXLk/jFOVWJZJ+e7lWQcCw1MqpFhxaM/l2LtzJ4evDvJhssD3gkMQeBDW"
    "2bamk/UrWhmbchpntADsd8NRU9dqio5NEs2eDcvpaElz4sBmejuXsrGnnWRLDhA8zb9k/6Vb"
    "8wEAsVZ8my5ycWAze3dsIvJ8lI6JlKYWaaqlMtlMioJdBcNcCNBaYzuSkqzj1zxcL1j4ikIQ"
    "RApM0WgZzBKoSInrBbPpL/K2YaTmjVlzVVs61P0AYw5AAKZpIITASiXQOoY5egNgxrEqSmnW"
    "Ax8rmaBJKZKJBBAzUXKlEsbId7uSL1uto909q0Z/LHBgmA8jzCNljy+/bH/k089K/vW3wuip"
    "gR3PF93nf9VvkGIeb0nCX1AAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
select = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B"
    "AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAadEVYdFNvZnR3YXJlAFBhaW50Lk5F"
    "VCB2My41LjEwMPRyoQAAAcxJREFUOE+dkUtLAlEUxw8YCEXYItIk7GFIuxatWlWbvkIfItpF"
    "rXJGetnDNHUaddSyosdHKCIIJNKIalFEDw0KorLHMgs83XM1sZweNPCbw9y5////3HPBZrNB"
    "o+kGtdpMR73xHnWAFbWGR17rjSleTfpnpH1qZF8ALWpVA23thd9qAKUCS1H7WYi55g5LS9Hw"
    "dT2f8hsaTVen2jpUlr19e74PRFGEKt0LlkPGIlitIAiEwAEtLHWriQrhG8HcOr+4DOHIIiih"
    "CPgCIZDkQHaITQ3XvIu66odcTbG5ZPS5+Zhq9Q8YDM9xSOxXwjDjU8Aj+bIGZSUrPVQ/zll4"
    "C9l0aCHxVjTKTSj9k8F3kDgcWQAmYu36Mf2axvjuLjeh9n80EJnYah1g7YZA9ivg8kh4e3eP"
    "5xcJjMXi3MTtldUNKFn2B1mbAfDO+DhTLjdeJC5x/+CQmSQxur3DTYrEdGV0VW5JhmmPlGdy"
    "yoVHxyd4dp7ApeVVnHA4kZk+FYlZq+Cc9lDiJ0iwtr6BSnAWE8lL7O3rD7HhNn8xEFgSbXYV"
    "IYiDm/ZxBw4Itr3T0zMcGrFfUdCfDdhjputkWNjwcHh0AkfHHLT+r4eMGADvsz2fvKjXDoYA"
    "AAAASUVORK5CYII=")

#----------------------------------------------------------------------
forward = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABsElEQVR4nLWSvUsjQRyG3zXn"
    "7iar2WjWTaIWwoqG2OjBFWd7Egu9D1ALrazkCosD/SPExlIsjKVgY+8fYGWlV0QFsZC9YMAz"
    "yWyyOx+7NgnRGLwg3AtTDPM+D8NvBvhfUbPGkDIT//CvXtcbZ6tSl3RrrAz/fK+AAhiyxs3d"
    "6a1PR+nNTLRjgfrdTCKEBAAIESCVii0lEvpZemNiqrUrAYA6P7CNkGRJkmQBsAD0QALCSjfG"
    "MkmYSR2cB3AIdQt/Hn9d7vzeeynIGtUeQw1bGRMRTUYkIkNRZAQ+wFlQXz44C8Coj2KxdFgh"
    "7pq9f0UaU3Y0TQmPjg80AR5A1KFWSa/Wu+y5IgLgR0NAOBUGo82SqEueg5wF4DRAtereUsbW"
    "AaApYD4YfQa3gvV9tUYLZUKydu7qro2g3bWbolqN/q04ZNbOXV43htgQ5DgXH5nny57L4RCv"
    "4FS8QunBmZQVBbquw3WZUyZk3j7In796RgDQFwYno4YWF0xc2Lmbe20u8VkwcRozYoj193ll"
    "p/LNPsiftPs3baN8iUfVrHEcXxphqdX0Ysdga8JfzYl3w53kCesjCFNgR8pXAAAAAElFTkSu"
    "QmCC")

#----------------------------------------------------------------------
home = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAClklEQVR4nI2TS0wTURSG/7l9"
    "0JkOWAgtD1EBNSAGDRRNwJgSIq6MCxZGjfuGrbInIQ1rTXQl0RjFKNGFrozP+EwaAtqChAXy"
    "LqSUDp2WMtN27r0uiiORavyTu7h/zvn+nJx7gQLy+XykkF9Ilj+N/v7+883NzR+7u7sbmpqa"
    "osFgMPIvgLDzMjAwcFmSpHsArNsWBzCRyWSGQqHQ/ZGRkcRfAYFAwC+K4i0AFsYYBOE3WxRF"
    "1B9uWP0+Eb7Ud+3q+10jDA4O9jkcjhucc8I5hyAIJkCSJLR1+FB35Hixy1V65WSbN6smNr4s"
    "Li7mAX6/v8ftdt/mnAuEELORcw5ZltF2qhMVNfVgjEEqcZFSd+WZqorylj3FxS/C4ZBuyeVy"
    "0x6Pp9dut8tWqxWccxBC4JRleDs64dlbi/mlZUTWFGQzWbhKy+Curm1wio4LNdWVb0k4HOaC"
    "IKTj8TgURcnPLEnwdnTCXX0AlHIIhIAJAnKUwqAcxGJHY0u7lN7Sor/2rRFCoOs61tZiqD3U"
    "iPKqfaCMwWAMot2GMlmEUxJNj3Fs3b0zFCMAYFCuAYAgCGCMQlWToJSbZzMeRWRqFPHIPAzK"
    "YVAGSpkGAAQAHk5uaAmdmquhlJpJlDHMjb/Bwrd3SClR0HwzKGO6CYilsi+Hwxt8Sc3mAYzB"
    "2E43KIOjyA7ZKcJqs8GgDCkth8lVVYf54oLDAf3ExcSTKfV6V51sOWqmcESTGiw2G2SnhE/L"
    "KXyYncZSUkN6M70DAACjj26y1p7I61k8YKF16XPRGhZUHckcQ6/DihKnyJfXs8qPhPJVS6pj"
    "uZWZV7v+AgDg2Ln2itau5/u9p5FMbY6nlNjY2UxwTFuZGX/89NncrvpCIgfbpf8qBPAT0nJI"
    "dXaKXEoAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
move = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAMAAAC6V+0/AAAAB3RJTUUH0wkLDiwV3B2DHgAA"
    "AAlwSFlzAAALEgAACxIB0t1+/AAAAARnQU1BAACxjwv8YQUAAADbUExURQAAAAAJUMPS3LLE"
    "0LLEz6C0w22Gm+fy9+Tw9uXy9+Xw9tvp767AzOHr8ejy9unz9+jz9+fz9+fx9sTT3Nbg5eTu"
    "8uny9+rz98/c5IqdrOXt8ebu8uv0+Oz0+erz+eDr8bbEze/1+ez0+O31+ez1+evz+dLe5JKi"
    "riYmJufv8+70+Ov0+evz9+Ls8bvIz/L2+u/2+vD2+u71+c3Y3vX5+/P4+/D1+djh5Z6qsvD3"
    "+sLM0PL3+u70+eTr7/H3+vD2+e/2+fD1+vL5+uvy9fb6/PT5+/T4+/H2+fb5+8VqdPEAAAAB"
    "dFJOUwBA5thmAAAAwklEQVR42pXO6VLCQBAE4G05lSORK2AScFmVUcMVILAcCcgh7/9EpACT"
    "AFVU2T+/6poexu6G6BZov0teOG22oJ0L9xcR/HFBUsJbg4Vlcj1ID8slaBWUaSbhOOA25guE"
    "M9Lhth/o0xPScER0MrM5npyx2+sTt4UQpmEM/k7S5xf3SXxbVrsT7IA3hXh71zTloxXii26Y"
    "dU1TG6+R71EqV3xTq7UIMuTyivpcKEbN11T68SmTvcKHWDyeSF4iwzHsnzkAagAWW9+fYeMA"
    "AAAASUVORK5CYII=")

#----------------------------------------------------------------------
subplots = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAANkE3LLaAgAAAq5J"
    "REFUeJx9kV1MUmEYxx85RxHRmJramtNMWrOPq0Zz3njFYgGzuem40C5aZXfOTSd9uGwmHtlk"
    "Njc2K5t2oyPdqhsTFhgHxRoUU88xj5WQIiKYokDhwd4uGk0Fe+7e3/7///PxJgEA6HS6FABI"
    "qa6uDsIhZbfbC02m8Z5oNHpKqWwuiXEOAIBIJCoOh8NLWq32cSIzRVH1ZjPprK2tkfP5WQUJ"
    "OywvL993u93bBEEQe7nVaj3R1aVBHo8H9fQ8CcU4TdNqkiRvcmIgPz//AUmSDVwu93pVVRUW"
    "4xiGCQEQRCIRqKi4FCQIwjkzM6MxGiebRkdHlZy93RQKxdOioqLbZWVlvhgLhUJfEEIQDocB"
    "x/FchUKRazAYGiorL+9GImwg4Tp6vf6uWq32AgB0dz8yMwyDaJpGNE0jl8uFnE4namxsmgYA"
    "SEqY8DekkaKoDqlUikejLLAsGxgcHFpHCDCWZX0aTZcIAAA/LMBimayXy2W4wWAAwcnzH2jS"
    "mEcQRPFBXdwEJpMJn5iwrojF4pydX0GY9uNgQadBWCDobbvIvXVQv++IOp0OI0mLWy6T5WRn"
    "Z4JnbX2u5YVrbNbBwOc5Z13LxOa9QwMcDgefYRZ8Mpk8Nz2DDyzL+mlqbuvHUI1k/v2UiWFW"
    "gV7wtjWbN+/EBdhstmS73U5JpdLMtLRUwDDs9/DwyEpra0spAMCO1yOf//iJ/vZ1DRYXve3N"
    "4xvX9t1ApepYl0gk6Txe6jaGYdkDA89ftbc/vLJv1vLeo8lpyHz2wpkSoTAPCguPXd3OCI5w"
    "AAC43JQsgeDIFI/HW+3re/Y9zgwA8K7On8Hxi6fts0vMwhos+X5qOcG8pn+/0NnZiQKBwIZK"
    "pcqKM++pN28D4zf6X5eXnstUHuHu9v9Pm7Be6n3Hx4xbttj7Dy0bOFu5z5J6AAAAAElFTkSu"
    "QmCC")

#----------------------------------------------------------------------
zoom_data = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACcElEQVR4nIWTy08TQRzHv7Pd"
    "R19baikEE0oINkGUCNWDooaExIse8UI14R/wwIn/wQuJB2IgHrwRJRKjGI0HBdTEphIjKRCr"
    "Eqpi5VVYl9nudh8dD4VCCwnf5Jt5ZPKZ78xvhgDAwMCdC+c727sDAX9ADvhlSZICkiTKkluU"
    "OY4EMpmsa3o6eXtoaCiDKvEAcK699Vr/rRt3QQhACIDdlhAwQhAMhlAbbnpFKb06OjqaOwjg"
    "AEDT8hoYQ9nY7xPGIIoioqeip/v64pPxeNx7FIBWAKohABMEAdFotKu39+aj4xNUQbweF7Gt"
    "VdTUFBDrjFzv6ekmFXdQTnBA/1QNqcUMdN1CY6QBTZEwfD4PCsGAMTX1jlUDtNJupcnf2Q28"
    "eP0JLW2X0Xz2DAjhMP9zG40nchD4onHEEXTKdmM7joPHE2/Q0nYFrW0dUPIC/my5wElhLK/7"
    "YZmWfgiQ13XKnCIAhuVMFkahCG9dOxZXgG1aKqfNCDxyHXI5tSIBDwCGYWi2bUPkBKjqDjxy"
    "GDuGC7wLcIv7dsGBzZzDCUzTpKZpAYyhOdIAPa9CFBi8bpTt8wCW9hehoHwYYFlW3jStIhhD"
    "qEZGV0cjXNYqfG6U7AFsYwtPxh7iy1y6cBBQrufaj496fTjo3nvGv1YVZKkfhHdD4gz4OAXj"
    "Ey+hqAWbUjo4MjJyrwKQTX/YPFkfqq38B6UlhCMoMoKcoqr3H4ynNrfoJQD9w8PDY/wewLEd"
    "CsZqSyMGTTeLOYWm1zaUxPzXpURydi7x7fvSwtupGScWi13keX6xIsHszPP3bkmgmZX1RPJz"
    "KpFaSCefPpvcxjH6D2k3O6c42VTiAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
zoom_to_rect = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGOfPtRkwAAACBj"
    "SFJNAACHDwAAjA8AAP1SAACBQAAAfXkAAOmLAAA85QAAGcxzPIV3AAAKOWlDQ1BQaG90b3No"
    "b3AgSUNDIHByb2ZpbGUAAEjHnZZ3VFTXFofPvXd6oc0wAlKG3rvAANJ7k15FYZgZYCgDDjM0"
    "sSGiAhFFRJoiSFDEgNFQJFZEsRAUVLAHJAgoMRhFVCxvRtaLrqy89/Ly++Osb+2z97n77L3P"
    "WhcAkqcvl5cGSwGQyhPwgzyc6RGRUXTsAIABHmCAKQBMVka6X7B7CBDJy82FniFyAl8EAfB6"
    "WLwCcNPQM4BOB/+fpFnpfIHomAARm7M5GSwRF4g4JUuQLrbPipgalyxmGCVmvihBEcuJOWGR"
    "DT77LLKjmNmpPLaIxTmns1PZYu4V8bZMIUfEiK+ICzO5nCwR3xKxRoowlSviN+LYVA4zAwAU"
    "SWwXcFiJIjYRMYkfEuQi4uUA4EgJX3HcVyzgZAvEl3JJS8/hcxMSBXQdli7d1NqaQffkZKVw"
    "BALDACYrmcln013SUtOZvBwAFu/8WTLi2tJFRbY0tba0NDQzMv2qUP91829K3NtFehn4uWcQ"
    "rf+L7a/80hoAYMyJarPziy2uCoDOLQDI3fti0zgAgKSobx3Xv7oPTTwviQJBuo2xcVZWlhGX"
    "wzISF/QP/U+Hv6GvvmckPu6P8tBdOfFMYYqALq4bKy0lTcinZ6QzWRy64Z+H+B8H/nUeBkGc"
    "eA6fwxNFhImmjMtLELWbx+YKuGk8Opf3n5r4D8P+pMW5FonS+BFQY4yA1HUqQH7tBygKESDR"
    "+8Vd/6NvvvgwIH554SqTi3P/7zf9Z8Gl4iWDm/A5ziUohM4S8jMX98TPEqABAUgCKpAHykAd"
    "6ABDYAasgC1wBG7AG/iDEBAJVgMWSASpgA+yQB7YBApBMdgJ9oBqUAcaQTNoBcdBJzgFzoNL"
    "4Bq4AW6D+2AUTIBnYBa8BgsQBGEhMkSB5CEVSBPSh8wgBmQPuUG+UBAUCcVCCRAPEkJ50Gao"
    "GCqDqqF6qBn6HjoJnYeuQIPQXWgMmoZ+h97BCEyCqbASrAUbwwzYCfaBQ+BVcAK8Bs6FC+Ad"
    "cCXcAB+FO+Dz8DX4NjwKP4PnEIAQERqiihgiDMQF8UeikHiEj6xHipAKpAFpRbqRPuQmMorM"
    "IG9RGBQFRUcZomxRnqhQFAu1BrUeVYKqRh1GdaB6UTdRY6hZ1Ec0Ga2I1kfboL3QEegEdBa6"
    "EF2BbkK3oy+ib6Mn0K8xGAwNo42xwnhiIjFJmLWYEsw+TBvmHGYQM46Zw2Kx8lh9rB3WH8vE"
    "CrCF2CrsUexZ7BB2AvsGR8Sp4Mxw7rgoHA+Xj6vAHcGdwQ3hJnELeCm8Jt4G749n43PwpfhG"
    "fDf+On4Cv0CQJmgT7AghhCTCJkIloZVwkfCA8JJIJKoRrYmBRC5xI7GSeIx4mThGfEuSIemR"
    "XEjRJCFpB+kQ6RzpLuklmUzWIjuSo8gC8g5yM/kC+RH5jQRFwkjCS4ItsUGiRqJDYkjiuSRe"
    "UlPSSXK1ZK5kheQJyeuSM1J4KS0pFymm1HqpGqmTUiNSc9IUaVNpf+lU6RLpI9JXpKdksDJa"
    "Mm4ybJkCmYMyF2TGKQhFneJCYVE2UxopFykTVAxVm+pFTaIWU7+jDlBnZWVkl8mGyWbL1sie"
    "lh2lITQtmhcthVZKO04bpr1borTEaQlnyfYlrUuGlszLLZVzlOPIFcm1yd2WeydPl3eTT5bf"
    "Jd8p/1ABpaCnEKiQpbBf4aLCzFLqUtulrKVFS48vvacIK+opBimuVTyo2K84p6Ss5KGUrlSl"
    "dEFpRpmm7KicpFyufEZ5WoWiYq/CVSlXOavylC5Ld6Kn0CvpvfRZVUVVT1Whar3qgOqCmrZa"
    "qFq+WpvaQ3WCOkM9Xr1cvUd9VkNFw08jT6NF454mXpOhmai5V7NPc15LWytca6tWp9aUtpy2"
    "l3audov2Ax2yjoPOGp0GnVu6GF2GbrLuPt0berCehV6iXo3edX1Y31Kfq79Pf9AAbWBtwDNo"
    "MBgxJBk6GWYathiOGdGMfI3yjTqNnhtrGEcZ7zLuM/5oYmGSYtJoct9UxtTbNN+02/R3Mz0z"
    "llmN2S1zsrm7+QbzLvMXy/SXcZbtX3bHgmLhZ7HVosfig6WVJd+y1XLaSsMq1qrWaoRBZQQw"
    "ShiXrdHWztYbrE9Zv7WxtBHYHLf5zdbQNtn2iO3Ucu3lnOWNy8ft1OyYdvV2o/Z0+1j7A/aj"
    "DqoOTIcGh8eO6o5sxybHSSddpySno07PnU2c+c7tzvMuNi7rXM65Iq4erkWuA24ybqFu1W6P"
    "3NXcE9xb3Gc9LDzWepzzRHv6eO7yHPFS8mJ5NXvNelt5r/Pu9SH5BPtU+zz21fPl+3b7wX7e"
    "frv9HqzQXMFb0ekP/L38d/s/DNAOWBPwYyAmMCCwJvBJkGlQXlBfMCU4JvhI8OsQ55DSkPuh"
    "OqHC0J4wybDosOaw+XDX8LLw0QjjiHUR1yIVIrmRXVHYqLCopqi5lW4r96yciLaILoweXqW9"
    "KnvVldUKq1NWn46RjGHGnIhFx4bHHol9z/RnNjDn4rziauNmWS6svaxnbEd2OXuaY8cp40zG"
    "28WXxU8l2CXsTphOdEisSJzhunCruS+SPJPqkuaT/ZMPJX9KCU9pS8Wlxqae5Mnwknm9acpp"
    "2WmD6frphemja2zW7Fkzy/fhN2VAGasyugRU0c9Uv1BHuEU4lmmfWZP5Jiss60S2dDYvuz9H"
    "L2d7zmSue+63a1FrWWt78lTzNuWNrXNaV78eWh+3vmeD+oaCDRMbPTYe3kTYlLzpp3yT/LL8"
    "V5vDN3cXKBVsLBjf4rGlpVCikF84stV2a9021DbutoHt5turtn8sYhddLTYprih+X8IqufqN"
    "6TeV33zaEb9joNSydP9OzE7ezuFdDrsOl0mX5ZaN7/bb3VFOLy8qf7UnZs+VimUVdXsJe4V7"
    "Ryt9K7uqNKp2Vr2vTqy+XeNc01arWLu9dn4fe9/Qfsf9rXVKdcV17w5wD9yp96jvaNBqqDiI"
    "OZh58EljWGPft4xvm5sUmoqbPhziHRo9HHS4t9mqufmI4pHSFrhF2DJ9NProje9cv+tqNWyt"
    "b6O1FR8Dx4THnn4f+/3wcZ/jPScYJ1p/0Pyhtp3SXtQBdeR0zHYmdo52RXYNnvQ+2dNt293+"
    "o9GPh06pnqo5LXu69AzhTMGZT2dzz86dSz83cz7h/HhPTM/9CxEXbvUG9g5c9Ll4+ZL7pQt9"
    "Tn1nL9tdPnXF5srJq4yrndcsr3X0W/S3/2TxU/uA5UDHdavrXTesb3QPLh88M+QwdP6m681L"
    "t7xuXbu94vbgcOjwnZHokdE77DtTd1PuvriXeW/h/sYH6AdFD6UeVjxSfNTws+7PbaOWo6fH"
    "XMf6Hwc/vj/OGn/2S8Yv7ycKnpCfVEyqTDZPmU2dmnafvvF05dOJZ+nPFmYKf5X+tfa5zvMf"
    "fnP8rX82YnbiBf/Fp99LXsq/PPRq2aueuYC5R69TXy/MF72Rf3P4LeNt37vwd5MLWe+x7ys/"
    "6H7o/ujz8cGn1E+f/gUDmPP8usTo0wAAAAlwSFlzAAALEgAACxIB0t1+/AAAABp0RVh0U29m"
    "dHdhcmUAUGFpbnQuTkVUIHYzLjUuMTAw9HKhAAAB3ElEQVQ4T5WTbU/aUBTH+VjEfQPdZxDZ"
    "+/p68GZB4hIVNAV1T7plU5z4EETdEqYmGoeOvRgzQZ2FTJfJ1irIQ4XWIvx3z00g1qqZJ/kn"
    "t/9z7u+etvfYcCUMw8Dq+gZejr3mWmNr8u4KWzP5eWsbnn4fPiW+InWc5Yptf+HeJsvdFhyw"
    "Gd/C2PswJFnBr3wefwpFpJUT/kx6FZrmNTeFTdM09PoGcXiaQ8/TfkyEwiaRRznvgB9Uez1s"
    "sZVVxJPf8bdYgl98jtSPnyaRd3xWQPxbErGVNSsgEByBzDYXKhUEn43j6LdsEnlKqcwOKCIw"
    "PGoFiIFh5NRzlFh7L8bfIndWMom8/HkFp2UVIjvM8gpLHz5iZ28fZU3Hm3dT0C8Mk8ijXDK1"
    "i2VWawHIsgzfkAjNqN36ESnX5xsC1VoAtVoNkYUoItFFXNbrN2o+EoXD+QhiIIhGo2Fi8Hug"
    "qipm5+bhZ51IUhp1VlRnsIMDCf5BET3eXrS1PYDL5WJymyCtm1itVtlmCZOhKTzxeLloTZ6i"
    "KHB0OWG32+F2u/H4CqQFoE6oPV3XQTASrckjZbNZdDq6LBAT4K6huQ4RBAHT4Rn8N6DZIXUi"
    "CN1o73iIBBu8ewGaEPqdmUyGz8Y/d/qJcLWhfigAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
scroll_left = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xhBQAAAAlw"
    "SFlzAAAOwgAADsIBFShKgAAAAAd0SU1FB9kDBxMOJJ9ycVgAAAAadEVYdFNvZnR3YXJlAFBh"
    "aW50Lk5FVCB2My41LjEwMPRyoQAAAohJREFUOE+Vk28s1HEcxz0UkdrK1rBVDzywFv1ZJZvZ"
    "Ggux6qINrSRbbKX0Z50o8p9c8+caqbhTuepSOFryJ87ZjvzrRKI1TPKvHhThwavfXcNusurB"
    "e+/t/X1/Xw++38/HBDD5k7Sjc2hG5mgSpPeO8TmhtrS75HJ5/zSK3mnUwzM0Ds8KPmvw2qEZ"
    "CrqnaB+bNQIZAfLbvnGz5SsV/T9QCdL7vFT93w1ZbOME6sGpBcgCoOTtBGGlA+Q2jyNvn0Te"
    "8VsKIVfqJpAJWVn3JEn1n4moHOLT5E8DZAFwXK4j4H43CdUDpNcNkiZIrh1kcGyS3Nfvqesd"
    "pXdohIulPQQ+6CG9dmARUPvuC+5pDXhmawmWtXPusY6Hmg+09vQhLtag1n2kpFHIFa2I8t7g"
    "JW1GlNu8CJBWdrEzSoVzfDVuydUoGzoprKgnLL+GxrYuomUv8Zeq8ZY0GDp67Y6rWgTEFTWx"
    "IUSGw/ln7Il6SrWmhXCpitDMMppaO/FKKMXpcplw/hyHC4IEtzulWAQUvujA1CMV66N3sT0p"
    "xy44j3vl9aQo6tgaJkXT0Y1/cgnrT8iwCZGz7lgB1oG3jR9xpWsMFt43WCXKYbX/LSwPZXJa"
    "8ogKdTv2gRkoa7TEyl5hdTgbK1E2omtKY0CgWIap8yXMPZKw2J+BhY8EcwHoGp6NS3gOZp4p"
    "hCYVYSNKwyEoiyptnzFA/6eb3MWY7ohghWs05nvjMXdPNADN3JNY45XCRj8JjgEZREsrlg7S"
    "/Jw7+sZgtiUUy11nWesmxnZfLPYHEtksSmS7XwJnUp8sP8rzkIORd3D2j8fJR8w23yu4HLmO"
    "d1gWQVeLicyq/DtguQ39p238n8v67i/znNNoCcN+uwAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
scroll_right = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xhBQAAAAlw"
    "SFlzAAAOwgAADsIBFShKgAAAAAd0SU1FB9kDBxMOJJ9ycVgAAAAadEVYdFNvZnR3YXJlAFBh"
    "aW50Lk5FVCB2My41LjEwMPRyoQAAApJJREFUOE+Vk2ss1WEcx71LpLRWmqXWvGhNLe3YKrVZ"
    "bRiKaQc1ajJr8YZ2klIIByOX5XYq1ThMuZXEYUzI5eTS4SSXNYflmCmXrBXDi0//c2rODG29"
    "+O77PL/LZ789e35GgNF66vy2TPvkMkpBOldPLwtla2vXNFdpFij+vEDrxCJtE0uCL+m9cXyR"
    "vMF5eqeWVoFWAZ70zPGg+zsKzU+qNb9QjAjSuaBqIVYlKKZthlbt/ApkBfCqb4bgyjHyeqYp"
    "6ZtCrp6lcnAWuXAvEM569c6S8G6S0JrxtYArBZ/wLRoio2mE8ek5nnePUdHzhdHJGTKaR0lt"
    "1pLSpCWsagQ/oS6lcUwP0U/QOPAVp/stuGZ1EiDvJbxUReeAhpK2QeJfdtA/PEqKog9JWT/i"
    "xx9wy+lC/KjLAMip6efYnWrspQ2cjG/AK7sdn6xmcqvbqWpTEyirp06pIqWiA/u4en3didh6"
    "AyC2UMn+QDk2Nyr+KOw1ottvuCY0KlVqXGNKya5UUlTbwiFJqT6/N6jYAMivVWPsnIzF5WdY"
    "BRZgGZBPdGEzJXUtHAzMQPF+gJuyciz9c9kj5Hf552Hhl2sAaCZm2eIQhdm5VHZflFH2VkXk"
    "w3JEQTKUH4c4E5LJNq9szL1lgudgLs5CfK/cANA9pF+EnM324Yj803ENzcDYJQl/aSH7xFLM"
    "3NP/Ko0dnunY+GVS3zm8GjA58wNrpwg22YVi4hCJqaMUE8cETJ0TMXVKZLtbEtbe6dj6phGZ"
    "o1j7D3RTqIa02HpEYXLkKluPX2fn6QisXGI44JnAYXECdt7xhCSXbfyVdZBbsjrOS55i7yPl"
    "qHsEIo+7nLoQx9ngTC5Fv0CSWfNvwEbbuVF83VX+H8hvTujUdXpf4qwAAAAASUVORK5CYII=")

