"""Subclass of clsCreateVariable, which is generated by wxFormBuilder."""

import wx
import clsCreateVariable

# Implementing clsCreateVariable
class frmCreateVariable( clsCreateVariable.clsCreateVariable ):
	def __init__( self, parent ):
		clsCreateVariable.clsCreateVariable.__init__( self, parent )
	
	# Handlers for clsCreateVariable events.
	def OnBtnCreateButton( self, event ):
		# TODO: Implement OnBtnCreateButton
		pass
	
	def OnBtnCancelButton( self, event ):
		# TODO: Implement OnBtnCancelButton
		pass
	
	
