"""Subclass of AddPoints, which is generated by wxFormBuilder."""

import wx

import odmtools.view.clsAddPoints as clsAddPoints



# Implementing AddPoints
class AddPoints(clsAddPoints.AddPoints):
    def __init__(self, parent):
        #super(AddPoints, self).__init__(parent)
        clsAddPoints.AddPoints.__init__(self, parent)

    # Handlers for AddPoints events.
    def onAddBtn(self, event):
        value = str(len(self.olv.GetObjects()) + 1)
        self.olv.AddObject(self.sampleRow())
        self.sb.SetStatusText("Added %s" % value)
        event.Skip()

    def onDeleteBtn(self, event):
        if self.selectedObject:
            self.olv.RemoveObject(self.selectedObject)
            self.sb.SetStatusText("Removing %s" % self.selectedObject.dataValue)
        object = event.GetEventObject()
        print "Selected Object", object
        self.selectedObject = None

        event.Skip()
    def onUploadBtn(self, event):
        event.Skip()
    def onFinishedBtn(self, event):
        event.Skip()

    def onSelected(self, event):
        object = event.GetEventObject()
        self.selectedObject = object.innerList[object.FocusedItem]

    def sampleRow(self):
        return self.Points()


class Example(wx.Frame):
    def __init__(self, parent, *args, **kwargs):
        wx.Frame.__init__(self, parent, *args, **kwargs)
        m = AddPoints(parent)
        m.Show()


if __name__ == '__main__':
    app = wx.App(useBestVisual=True)
    ex = Example(None)
    app.MainLoop()