"""Subclass of AddPoints, which is generated by wxFormBuilder."""

import wx
from odmtools.controller.frmBulkInsert import BulkInsert
import odmtools.view.clsAddPoints as clsAddPoints



# Implementing AddPoints
class AddPoints(clsAddPoints.AddPoints):
    def __init__(self, parent):
        #super(AddPoints, self).__init__(parent)
        clsAddPoints.AddPoints.__init__(self, parent)
        self.frame = BulkInsert(self)


    # Handlers for AddPoints events.
    def onAddBtn(self, event):
        """

        :param event:
        :return:
        """
        self.olv.AddObject(self.olv.sampleRow())
        self.sb.SetStatusText("Added a row")
        event.Skip()

    def onClearAllBtn(self, event):
        """

        :param event:
        :return:
        """
        if len(self.olv.GetObjects()) < 1:
            wx.MessageBox("Nothing to remove here", " ", wx.OK)
            return
        msg = wx.MessageDialog(None, 'Are you sure you want to delete your work?', 'Clear Everything?', wx.YES_NO | wx.ICON_WARNING |wx.NO_DEFAULT )
        value = msg.ShowModal()
        if value == wx.ID_YES:
            self.olv.SetObjects(None)
        return

    def onDeleteBtn(self, event):
        """

        :param event:
        :return:
        """
        try:
            if self.selectedObject:
                if len(self.selectedObject) > 1:
                    length = len(self.selectedObject)
                    self.olv.RemoveObjects(self.selectedObject)
                    self.sb.SetStatusText("Removed %s items" % length)
                else:
                    self.olv.RemoveObject(self.selectedObject)
                    self.sb.SetStatusText("Removing %s" % self.selectedObject.dataValue)
            self.selectedObject = None
        except TypeError:
            pass

        event.Skip()

    def onUploadBtn(self, event):
        """

        :param event:
        :return:
        """
        if not self.frame.IsShown():
            self.frame.CenterOnParent()
            self.frame.Show()
        else:
            self.frame.Hide()

        event.Skip()
    def onFinishedBtn(self, event):
        """

        :param event:
        :return:
        """
        event.Skip()

    def onSelected(self, event):
        object = event.GetEventObject().GetSelectedObjects()
        try:
            if len(object) > 1:
                self.selectedObject = object
            else:
                self.selectedObject = object[0]
        except TypeError:
            pass


class Example(wx.Frame):
    def __init__(self, parent, *args, **kwargs):
        wx.Frame.__init__(self, parent, *args, **kwargs)
        m = AddPoints(parent)
        m.Show()


if __name__ == '__main__':
    app = wx.App(useBestVisual=True)
    ex = Example(None)
    app.MainLoop()