"""Subclass of clsCreateVariable, which is generated by wxFormBuilder."""

import wx
from  odmtools.view.clsCreateVariable import clsCreateVariable
from odmtools.odmdata import Variable

# Implementing clsCreateVariable
class frmCreateVariable(clsCreateVariable):
    # Handlers for clsCreateVariable events.
    def __init__(self, parent, service_man, old_var=None):
        self.service_man = service_man
        cv_service = self.service_man.get_cv_service()
        self.series_service = self.service_man.get_series_service()

        clsCreateVariable.__init__(self, parent)
        self.__init_boxes(old_var, cv_service)

    def __init_boxes(self, old_var, cv_service):

        if old_var:
            name_list = [old_var.name]
            var_unit =  [old_var.variable_unit.name]
            time_unit =  [old_var.time_unit.name]
            sample_list = [old_var.sample_medium]
            spec_list = [old_var.speciation]

        else:
            name_list = [x.term for x in cv_service.get_variable_name_cvs()]
            var_unit=['units']
            time_unit=['units']
            sample_list =[x.term for x in cv_service.get_sample_medium_cvs()]
            spec_list =[x.term for x in cv_service.get_speciation_cvs()]

        val_type =[x.term for x in cv_service.get_value_type_cvs()]
        data_type =[x.term for x in cv_service.get_data_type_cvs()]

        self.cbVarName.AppendItems(name_list)
        self.cbVarUnits.AppendItems(var_unit)
        self.cbTSUnits.AppendItems(time_unit)
        self.cbSampleMedium.AppendItems(sample_list)
        self.cbSpeciation.AppendItems(spec_list)
        self.cbValueType.AppendItems(val_type)
        self.cbDataType.AppendItems(data_type)





    def OnBtnCreateButton(self, event):
        var = self.createVariable()
        if self.series_service.create_variable(var):
            self.Destroy()
        else:
            wx.MessageDialog("Variable was not create", "", wx.OK)

    def createVariable(self):
        v = Variable()
        v.code = self.txtVarCode.GetValue()
        v.name = self.cbVarName.GetValue()
        v.speciation = self.cbSpeciation.GetValue()
        v.variable_unit_id = self.cbVarUnits.GetValue()
        v.sample_medium = self.cbSampleMedium.GetValue()
        v.value_type = self.cbValueType.GetValue()
        v.is_regular = self.cbIsRegular.GetValue()
        v.time_support = self.txtTSValue.GetValue()
        v.time_unit_id = self.cbTSUnits.GetValue()
        v.data_type = self.cbDataType.GetValue()
        v.general_category = self.txtGenCat.GetValue()
        v.no_data_value = self.txtNoDV.GetValue()

    def OnBtnCancelButton(self, event):
        self.Destroy()



