"""Subclass of MyFrame1, which is generated by wxFormBuilder."""

import wx
import pandas as pd
import gui_imp
import matplotlib
import matplotlib.pyplot as plt
matplotlib.use('WXAgg')
from matplotlib.backends.backend_wxagg import FigureCanvasWxAgg as FigureCanvas
from matplotlib.backends.backend_wx import NavigationToolbar2Wx
from matplotlib.figure import Figure

import wx


# Implementing MyFrame1
class MyProject1MyFrame1( gui_imp.MyFrame1 ):
    def __init__( self, parent ):
        gui_imp.MyFrame1.__init__( self, parent )
        self.readData()
        self.figure = Figure()
        self.axes = self.figure.add_subplot(111)

        self.axes.plot(0,0)
        self.canvas = FigureCanvas(self, -1, self.figure)
        self.figure.canvas = self.canvas

        self.sizer = wx.BoxSizer(wx.VERTICAL)
        self.sizer.Add(self.canvas, 1, wx.LEFT | wx.TOP | wx.GROW)
        self.m_panel1.SetSizer(self.sizer)
        self.Fit()

    def readData(self):
        self.data = pd.read_csv("../sample file.csv", parse_dates = True, index_col = 4)

    def returnData(self):
        return self.data["DataValue"].values, self.data.index.values

    def onAdd(self, event):
        values, dates = self.returnData()
        self.axes.plot(dates, values)
        self.canvas.draw()
        print "adding again"

    def onRemove(self, event):
        plt.clf()
        plt.close()
        self.canvas.draw()
        event.Skip()
        print "removing again"




App = wx.App()
Frame = MyProject1MyFrame1(None)
Frame.Show()
App.MainLoop()