"""
This is a setup.py script generated by py2applet

to generate: 
	py2applet --make-setup
Usage:
    python setup.py py2app
"""

from setuptools import setup
#'arch': 'i386',
LIBS = ['/usr/X11/lib/libfreetype.6.dylib', '/usr/X11/lib/libstdc++.6.dylib', '/usr/X11/lib/libpng15.15.dylib']
APP = ['/Users/stephanie/ODMToolsPython/ODMToolsPython.py']
#DATA_FILES = ['']
OPTIONS = {'iconfile': '/Users/stephanie/ODMToolsPython/odmtools/common/icons/ODMTools.icns',
           'includes': ['pymysql', 'appdirs', 'matplotlib','sqlalchemy', 'dateutil'],
           'frameworks': LIBS
	   
}

setup(
    app=APP,
    #data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

# to add an icon py2applet --make-setup foo.py --iconfile images/icon.icns
# --arch i386 --includes wx, sqlalchemy, pymysql, matplotlib, ObjectListView , appdirs 
