
""" Subclass of clsEquation, which is generated by wxFormBuilder. """

import wx

from odmtools.view import clsEquation


# Implementing dlg_equation
class frmEquation(clsEquation.dlg_equation):
	def __init__(self, parent, series):
		self.is_applied = False
		self.recordService = series
		clsEquation.dlg_equation.__init__(self, parent)

	def onOK(self, event):
		print "OK!"
		self.Close()
		event.Skip()

	def onCancel(self, event):
		self.Close()
		event.Skip()

	def __del__( self ):
		pass