"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['ODMToolsPython.py']
DATA_FILES = [('', ['images'])]
OPTIONS = {'argv_emulation': True,
           'arch': 'i386',
           'includes': ['wx', 'sqlalchemy', 'pymysql', 'matplotlib', 'ObjectListView']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

# to add an icon py2applet --make-setup foo.py --iconfile images/icon.icns
# --arch i386 --includes wx, sqlalchemy, pymysql, matplotlib, ObjectListView  
